### ISSUE TITLE
svg format supported?

### ISSUE THREAD

**Issue by spger** [sammycage/lunasvg#10]
Hi I would like to know if Luna library can process this type of struct:

<svg width="450px" height="300px" xmlns="http://www.w3.org/2000/svg">

  <style type="text/css">
    text { font-size: 9; }
    rect { fill: none; stroke: blue; }
  </style>

  <defs>
    <g id="smile">
      <rect x='.5' y='.5' width='29' height='39' style="fill:black;stroke:red"/>
      <circle cx='15' cy='20' r='10'  fill='yellow'/>
      <circle cx='12' cy='17' r='1.5' fill='black'/>
      <circle cx='17' cy='17' r='1.5' fill='black'/>
      <path d='M 10 24 A 8 8 0 0 0 20 24' stroke='black' stroke-width='2'/>
    </g>
  </defs>
    <g >
      <svg preserveAspectRatio="xMinYMin slice" viewBox="0 0 30 40" width="100" height="160">
	<use href="#smile" />
      </svg>
    </g>
    <g transform="translate(50,0)">
      <svg preserveAspectRatio="xMidYMid slice" viewBox="0 0 30 40" width="30" height="60">
	<use href="#smile" />
      </svg>
    </g>
</svg>

**Comment by sammycage** [comment]
No.. Stylesheet is not implemented.

**Comment by spger** [comment]
Okay and this type of structure with "href":
 <g transform="translate(50,0)">
      <svg preserveAspectRatio="xMidYMid slice" viewBox="0 0 30 40" width="30" height="60">
	<use href="#smile" />
      </svg>
    </g>
