### ISSUE TITLE
Some files that render correctly with NanoSVG don't render correctly with LunaSVG

### ISSUE THREAD

**Issue by leonstyhre** [sammycage/lunasvg#101]
Hi! A number of files don't seem to render correctly with LunaSVG although they render fine with NanoSVG.

See these two example screenshots:
https://es-de.org/temp/LunaSVG_rendering.png
https://es-de.org/temp/NanoSVG_rendering.png

Here are some files that don't render correctly:
https://gitlab.com/es-de/emulationstation-de/-/blob/master/themes/slate-DE/arcade/images/logo.svg
https://gitlab.com/es-de/emulationstation-de/-/blob/master/themes/slate-DE/auto-favorites/images/logo.svg
https://gitlab.com/es-de/emulationstation-de/-/blob/master/themes/slate-DE/custom-collections/images/logo.svg

Thanks!

**Comment by sammycage** [comment]
Fixed : e0f786c9be6fae1ffabddfe56fb1e0a1a7eb775d

**Comment by leonstyhre** [comment]
Fantastic, thanks for the quick fix! It also fixes the splash screen image as I mentioned in the separate issue.
