### ISSUE TITLE
Default color in LunaSVG not the same as in NanoSVG

### ISSUE THREAD

**Issue by leonstyhre** [sammycage/lunasvg#102]
For files with undefined colors, by default these are set to 0xFFFFFFFF in NanoSVG but in LunaSVG they're set to 0x000000FF (or is it 0x00000000?)

Could this be changed so it works the same way as in NanoSVG? Numerous graphics files for my application that have been created by many persons rely on the default color being 0xFFFFFFFF. See these two screenshots which illustrate the issue:

https://es-de.org/temp/NanoSVG_default_color.png
https://es-de.org/temp/LunaSVG_default_color.png

If you don't want to change this for everyone, could you perhaps introduce a CMake flag or similar to set the default color to white?
Thanks!

**Comment by sammycage** [comment]
According to the SVG spec, the default for `fill` and `stroke` is opaque black and transparent black respectively

**Comment by leonstyhre** [comment]
But that's not how it's commonly implemented, here's another example from GitLab with the exact same image is also shown in white using their built-in renderer:

https://gitlab.com/es-de/emulationstation-de/-/blob/master/resources/graphics/splash.svg

**Comment by leonstyhre** [comment]
Sorry, you can close this issue, it was not caused by the default color as I thought, but rather the other parseStyle issue you just fixed! The image renders correctly now.

**Comment by sammycage** [comment]
Nice time with you....
