### ISSUE TITLE
cpack fails on Windows due to LunaSVG attempting to install static library into C:\Program Files

### ISSUE THREAD

**Issue by leonstyhre** [sammycage/lunasvg#103]
I have managed to get the library to build and work correctly on Windows using both MSVC and MinGW but I can't create the NSIS installation package as LunaSVG tries to install itself under C:\Program Files

I link statically so no installation should be attempted. Here's an example output:

```
C:\Programmering\EmulationStation-DE_MSVC\emulationstation-de>cpack
CPack: Create package using NSIS
CPack: Install projects
CPack: - Run preinstall target for: emulationstation-de
CPack: - Install project: emulationstation-de []
CMake Error at C:/Programmering/EmulationStation-DE_MSVC/emulationstation-de/external/lunasvg/cmake_install.cmake:42 (message):
  ABSOLUTE path INSTALL DESTINATION forbidden (by caller): C:/Program Files
  (x86)/emulationstation-de/include/lunasvg.h
Call Stack (most recent call first):
  C:/Programmering/EmulationStation-DE_MSVC/emulationstation-de/external/cmake_install.cmake:37 (include)
  C:/Programmering/EmulationStation-DE_MSVC/emulationstation-de/cmake_install.cmake:37 (include)


CPack Error: Error when generating package: emulationstation-de
```

The problem is identical when building using MinGW.

**Comment by sammycage** [comment]
I don't know how the windows build system works, you can get help elsewhere, eg stackoverflow

**Comment by sammycage** [comment]
Maybe `BUILD_SHARED_LIBS` flag might help

**Comment by leonstyhre** [comment]
Using BUILD_SHARED_LIBS doesn't help unfortunately. But I'll look more into this tomorrow and post here of my findings, I think you need to change something in your CMake configuration for this to work but I'll confirm that tomorrow.

**Comment by leonstyhre** [comment]
You can close this issue, it was a mistake made by me. I defined this:
```add_subdirectory(lunasvg)```
Instead of this:
```add_subdirectory(lunasvg EXCLUDE_FROM_ALL)```

Everything seems to work perfect now on Windows (I build as a DLL btw) and on macOS too. If you are able to fix the issue with the rlottie mixup and the rendering artifact problem I reported, then I think LunaSVG should be able to replace NanoSVG for my application!

**Comment by sammycage** [comment]
1. Rlottie's conflict has been resolved https://github.com/sammycage/lunasvg/commit/ead790126004b86a2dbbe9f4aaf27e82e419721e
2. I don't notice any artifacts on my side. #106
