### ISSUE TITLE
Edge artifacts (rendering issue)

### ISSUE THREAD

**Issue by leonstyhre** [sammycage/lunasvg#104]
There are some harsh edge artifacts getting rendered by LunaSVG that are not visible with NanoSVG. Maybe the antialiasing around edges is not working as it should or perhaps there is some other problem?

It's subtle but still clearly visible, see especially the "e" in the following images:

https://es-de.org/temp/LunaSVG_edge_artifacts.png
https://es-de.org/temp/NanoSVG_no_edge_artifacts.png

Here's a link to the logo:
https://gitlab.com/es-de/emulationstation-de/-/blob/master/themes/slate-DE/chailove/images/logo.svg

**Comment by sammycage** [comment]
I will investigate it tomorrow

**Comment by sammycage** [comment]
https://github.com/sammycage/lunasvg/issues/106#issuecomment-1277122926

**Comment by leonstyhre** [comment]
I just tried this with the latest commit ead790126004b86a2dbbe9f4aaf27e82e419721e and unfortunately the problem is still there, there are edge artifacts when rendering with LunaSVG but not when using NanoSVG. Or in other words, it looks exactly as in the images posted above using that specific logo (and for other SVG images as well).

**Comment by sammycage** [comment]
In Bitmap data each pixel is a 32-bit quantity, with alpha in the upper 8 bits, then red, then green, then blue. The 32-bit quantities are stored native-endian. Pre-multiplied alpha is used.

In short Bitmap format is BGRA(Pre-multiplied) in little endian machine and ARGB(Pre-multiplied) in big endian machine.

**Comment by leonstyhre** [comment]
I have done some testing now and I got the SVG images to render correctly without any edge artifacts. The problem was that I used your convertToRGBA() function to convert the image to RGBA format after rasterization and then the artifacts appear. If I instead keep the files in its native BGRA format and make the conversion in the fragment shader, then it renders correctly and looks just as nice as when using NanoSVG.

Is this due to a bug in convertToRGBA() or is there some extra step I need to perform that I missed? I'm considering changing to premultiplied alpha for all images in my application and in this case I could skip the use of convertToRGBA but at the moment it's a bit messy as I have to handle SVG and raster images differently due to the different formats used between these. So convertToRGBA() is currently a very convenient function for me, if it can be made to work correctly that is.

**Comment by leonstyhre** [comment]
I have rewritten my application now to use the BGRA pixel format instead of RGBA and I've changed to premultiplied alpha for all images (including raster images which also led to a speed increase as I could remove a format conversion step) so now everything works perfect! There may still be something wrong with the convertToRGBA() function but it could also been that I missed some step to get it to render correctly, and now I don't use it any longer. Regardless it's now working fine and as far as I'm concerned you can close this issue. Many thanks!
