### ISSUE TITLE
Another edge artifacts

### ISSUE THREAD

**Issue by Jelim16** [sammycage/lunasvg#106]
Hi, I noticed some render changes between versions 2.3.1 and 2.3.4:

![Diff](https://user-images.githubusercontent.com/99876075/195332111-a3d08ff2-0522-4157-8faf-0b6d6562b20c.png)

Original SVG:
![lock](https://user-images.githubusercontent.com/99876075/195332224-f5353861-07bd-47f2-a092-a5231ad590dc.svg)

**Comment by sammycage** [comment]
`svg2png lock.svg 720x0 0xFFFFFFFF`

I don't see any difference

# v2.3.1

![lock svg-v2 3 1](https://user-images.githubusercontent.com/29164324/195390975-5bd2949c-e187-4e28-a6b1-215a72cd056c.png)

# v2.3.4

![lock svg-v2 3 4](https://user-images.githubusercontent.com/29164324/195391158-37620f1d-8770-43cd-8490-3e4042dab333.png)

**Comment by sammycage** [comment]
#104

**Comment by Jelim16** [comment]
Oh I´m sorry. Problem was on my side. I had code in there that did premultiplication. I didn't realize that it's not necessary anymore. Thank you anyway.
