### ISSUE TITLE
Default fill color

### ISSUE THREAD

**Issue by Jelim16** [sammycage/lunasvg#107]
Hi, I would like to ask what is now the default fill color? In thread #102 you mentioned that it is an opaque black. Nevertheless LunaSVG renderes no shape from this image:
![arrowdown](https://user-images.githubusercontent.com/99876075/195842084-301767dd-d20c-4c96-bfc2-75115a644218.svg)
Am I missing something?

**Comment by sammycage** [comment]
Fixed
