### ISSUE TITLE
Build fails with vcpkg dependencies

### ISSUE THREAD

**Issue by zcream** [sammycage/lunasvg#11]
I have cairo installed via vcpkg. 

>cmake .. "-DCMAKE_TOOLCHAIN_FILE=C:\Users\Administrator\vcpkg\scripts\buildsystems\vcpkg.cmake"

Build still does not detect cairo.
[CMakeOutput.log](https://github.com/sammycage/lunasvg/files/5470255/CMakeOutput.log)

-- Found PkgConfig: C:/MinGW/bin/pkg-config.exe (found version "0.23")
-- Checking for module 'cairo'
--   No package 'cairo' found
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/FindPkgConfig.cma
ke:545 (message):
  A required package was not found
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindPkgConfig.cmake:733 (_pkg_
check_modules_internal)
  CMakeLists.txt:22 (pkg_check_modules)

**Comment by zcream** [comment]
@sammycage I think the problem is the cairo_DIR variable. What do you want it to be ? Are you using cairo as a shared lib or static linked?

**Comment by sammycage** [comment]
Take a look at the script.
```
if(LUNASVG_ENABLE_CAIRO)
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(CAIRO REQUIRED cairo)
    target_include_directories(lunasvg PRIVATE ${CAIRO_INCLUDE_DIRS})
    target_link_libraries(lunasvg ${CAIRO_LIBRARIES})
    add_subdirectory(source/backends/cairo)
```

**Comment by sammycage** [comment]
Removed : https://github.com/sammycage/lunasvg/commit/c06651ef0ca5fa975580b30c429e514306c248f6

Please consider using the current rasterizer. It is small, simple and fast.
