### ISSUE TITLE
Rendering issues/regressions (fill/pattern) ?

### ISSUE THREAD

**Issue by poire-z** [sammycage/lunasvg#118]
Upgraded from 637121f8 to your latest master, and I notice some rendering issues of stuff related to fill or pattern (I have no tool to inspect/isolate stuff in these complex SVGs, so sharing them and what I see, hope it's ok).
These issues were not there when I use your latest August commits.
I see nothing obvious that could cause this in your lunasvg/source/ changes (except possibly the CSS parsing refactoring that I did not get familiar with), so it may be stuff on the 3rdparty/plutovg side.

These are images from https://commons.wikimedia.org/wiki/User:JoKalliauer/SVG_test_suites/resvg_Issues_details, and the only 4 of themwhere I noticed some issues.
(These SVGs on this page are supposed to be problematic ones, causing issues with various renderers, so it might be ok if you fixed stuff to be more conforming to not have them working anymore :)
In my screenshots, left is with your August code, right is with current master.

----
![20 Feedbin-Favicon-tag](https://user-images.githubusercontent.com/24273478/200774752-ea7b92d2-1cb1-4514-8aac-247761507194.svg)
A single path, no viewbox/width/height. Now it does not render anything:
![image](https://user-images.githubusercontent.com/24273478/200775331-6ca8881b-498b-42db-8016-a72ba32711b1.png)

----
![22 Coa_Frankfurt-H%C3%B6chst_Test](https://user-images.githubusercontent.com/24273478/200775456-89d43e90-2321-4724-b020-0f623ec68a37.svg)

I think this one has patterns in the big red areas, and the patterns rendering was already a bit variable previously (when zooming/rerendering, possibly just some scaling/aliasing artifacts). But now, it's mostly white with some pieces missing. Moreover, when you zoom, bits appear or disappear, stuff get filled or unfilled. It feels there may be stuff uninitialized.
![image](https://user-images.githubusercontent.com/24273478/200775615-cebb8edb-2f6e-4072-b4c6-fa9209d38798.png)

----
![31 Manfeild_Autocourse_track_map_%28New_Zealand%29_TextOnPath_converted_to_Path](https://user-images.githubusercontent.com/24273478/200776064-bca11b47-bf3e-403e-b09b-5b156f25095b.svg)
The thing circled in yellow loses its pattern. Also, when zooming its filling color (which was absent in the previous result) varies from black to gray to white.
![image](https://user-images.githubusercontent.com/24273478/200776190-0305736b-c15a-485e-84f2-a7c107b62ece.png)

----
![52 Grundriss_Burg_Hageneck](https://user-images.githubusercontent.com/24273478/200776554-904cedbd-17a9-4d0d-b571-c89d95457c55.svg)
The gray/hatched pattern are missing:
![image](https://user-images.githubusercontent.com/24273478/200776670-62bc11ec-ebf8-4bcd-82a7-1ceeefe64768.png)

and when zooming/rerendering, I may get this from time to time:
![image](https://user-images.githubusercontent.com/24273478/200776911-c17d2b91-dfde-45ee-9cc4-e7eae9cefa2a.png)

----
Thanks again for this nice library and your recent fixes :)

**Comment by sammycage** [comment]
Fixed in commit 56ddf2a5a1353d8ec5bddaee08a89a7be60a86e0

**Comment by poire-z** [comment]
Thank you ! I can confirm the 3 last issues above are fixed.
The first one might be my issue (SVG in a HTML context) as it displays ok (icon displayed, and image size fitting the icon) when zooming on it.
