### ISSUE TITLE
Is there a time plan for an animated version?

### ISSUE THREAD

**Issue by coollofty** [sammycage/lunasvg#12]
This is a cool library, I found it by accident because I need to render SVG animation in my App, but unfortunately it does not currently support animation, otherwise I can happily introduce it to my ^_^

In addition, NanoVG is good, and there is hope that SVG can be rendered in real time. Have you considered using NanoVG?

**Comment by sammycage** [comment]
Thank you for your compliment. NanoVG cannot be used to render SVG.
