### ISSUE TITLE
Undefined Behavior Case 

### ISSUE THREAD

**Issue by m-carrasco** [sammycage/lunasvg#121]
Hi :wave:  

I'd like to report the following test case that triggers UB in [lunasvg](https://github.com/sammycage/lunasvg/commit/585d61eef24510bc0b7fe3d9e768d0675d4b5a6f).

The [file](https://github.com/m-carrasco/lunasvg/blob/a9c1441455feaf5386d3fa32385003f25debb0d6/test-cases/e-feMorphology-009.bmfull_rand_base.ts3.e18.s0.sid451.smtbit_opt_uc.svg) can be found here. The harness is a [slightly modified version](https://github.com/m-carrasco/lunasvg/blob/coverage/example/svg2png.cpp#L63) of svg2png. It calls `Document::loadFromData(buffer, size);` instead of `Document::loadFromFile(filename);`. The test case comes from fuzzing.

An important remark I think is that this test case is not rejected by [`Document::loadFromData`](https://github.com/m-carrasco/lunasvg/blob/coverage/example/svg2png.cpp#L63) or [`bitmap.valid()`](https://github.com/m-carrasco/lunasvg/blob/coverage/example/svg2png.cpp#L71).

Build settings:

1. `git clone -b test-cases https://github.com/m-carrasco/lunasvg.git`
2. `mkdir build && cd build`
3. `CXX=clang++-12 CC=clang-12 cmake -DLUNASVG_BUILD_EXAMPLES=ON -DCMAKE_CXX_FLAGS="-g -O0 -fsanitize=undefined,address -fno-sanitize-recover=all" -DCMAKE_C_FLAGS="-g -O0 -fsanitize=undefined,address -fno-sanitize-recover=all" ../lunasvg/`

How to execute:

1. `UBSAN_OPTIONS=halt_on_error=1:print_stacktrace=1 ASAN_OPTIONS=halt_on_error=1 build/example/svg2png lunasvg/test-cases/e-feMorphology-009.bmfull_rand_base.ts3.e18.s0.sid451.smtbit_opt_uc.svg`

Error log:

```
/lunasvg/3rdparty/plutovg/plutovg-blend.c:147:16: runtime error: -nan is outside the range of representable values of type 'int'
    #0 0x7a689f in gradient_pixel /lunasvg/3rdparty/plutovg/plutovg-blend.c:147:16
    #1 0x7a8948 in fetch_radial_gradient /lunasvg/3rdparty/plutovg/plutovg-blend.c:264:25
    #2 0x79a2b8 in blend_radial_gradient /lunasvg/3rdparty/plutovg/plutovg-blend.c:482:13
    #3 0x793c7a in plutovg_blend_gradient /lunasvg/3rdparty/plutovg/plutovg-blend.c:790:9
    #4 0x7903e5 in plutovg_blend /lunasvg/3rdparty/plutovg/plutovg-blend.c:701:9
    #5 0x768a21 in plutovg_fill_preserve /lunasvg/3rdparty/plutovg/plutovg.c:463:5
    #6 0x7683d4 in plutovg_fill /lunasvg/3rdparty/plutovg/plutovg.c:423:5
    #7 0x6d5957 in lunasvg::Canvas::fill(lunasvg::Path const&, lunasvg::Transform const&, lunasvg::WindRule, lunasvg::BlendMode, double) /lunasvg/source/canvas.cpp:100:5
    #8 0x69cf72 in lunasvg::FillData::fill(lunasvg::RenderState&, lunasvg::Path const&) const /lunasvg/source/layoutcontext.cpp:331:19
    #9 0x69f8b8 in lunasvg::LayoutShape::render(lunasvg::RenderState&) const /lunasvg/source/layoutcontext.cpp:408:18
    #10 0x691683 in lunasvg::LayoutContainer::renderChildren(lunasvg::RenderState&) const /lunasvg/source/layoutcontext.cpp:88:16
    #11 0x694e4e in lunasvg::LayoutSymbol::render(lunasvg::RenderState&) const /lunasvg/source/layoutcontext.cpp:159:5
    #12 0x5bb566 in lunasvg::Document::render(lunasvg::Bitmap, lunasvg::Matrix const&) const /lunasvg/source/lunasvg.cpp:343:11
    #13 0x5bcc85 in lunasvg::Document::renderToBitmap(unsigned int, unsigned int, unsigned int) const /lunasvg/source/lunasvg.cpp:368:5
    #14 0x5ad057 in main /lunasvg/example/svg2png.cpp:70:29
    #15 0x7f6c49fe1082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    #16 0x4e6d6d in _start (/lunasvg-build-ubsan-asan/example/svg2png+0x4e6d6d)
```

Thanks a lot for sharing this project!

Best regards,
Manuel

**Comment by m-carrasco** [comment]
Fixed error in building instructions. Now it points to the correct repository.

**Comment by m-carrasco** [comment]
Hi @sammycage :wave:

How are you? I just wanted to know if I could provide any extra information to help fix this bug.

From my understanding so far, I think the problem is that it was not rejected either by [Document::loadFromData](https://github.com/m-carrasco/lunasvg/blob/coverage/example/svg2png.cpp#L63) or [bitmap.valid()](https://github.com/m-carrasco/lunasvg/blob/coverage/example/svg2png.cpp#L71).

Do you have any opinions or thoughts on the cause of this issue?

Best regards,
Manuel

**Comment by sammycage** [comment]
> I just wanted to know if I could provide any extra information to help fix this bug.

I need this file `e-feMorphology-009.bmfull_rand_base.ts3.e18.s0.sid451.smtbit_opt_uc.svg`

**Comment by m-carrasco** [comment]
Hi @sammycage 

Here is the [file](https://www.dropbox.com/s/da3qegyqen25a9o/e-feMorphology-009.bmfull_rand_base.ts3.e18.s0.sid451.smtbit_opt_uc.svg?dl=0). 

I should have made it available easier; sorry for that.

Best regards,
Manuel.

**Comment by sammycage** [comment]
> Here is the [file](https://www.dropbox.com/s/da3qegyqen25a9o/e-feMorphology-009.bmfull_rand_base.ts3.e18.s0.sid451.smtbit_opt_uc.svg?dl=0).

This file contains some invalid characters.

**Comment by sammycage** [comment]
**There are no errors on my machine... Am I doing something wrong?**

<pre><font color="#26A269"><b>sammycage@ubuntu</b></font>:<font color="#12488B"><b>~/Projects/lunasvg</b></font>$ mkdir build &amp;&amp; cd build
<font color="#26A269"><b>sammycage@ubuntu</b></font>:<font color="#12488B"><b>~/Projects/lunasvg/build</b></font>$ CXX=clang++-12 CC=clang-12 cmake -DLUNASVG_BUILD_EXAMPLES=ON -DCMAKE_CXX_FLAGS=&quot;-g -O0 -fsanitize=undefined,address -fno-sanitize-recover=all&quot; -DCMAKE_C_FLAGS=&quot;-g -O0 -fsanitize=undefined,address -fno-sanitize-recover=all&quot; ..
-- The CXX compiler identification is Clang 12.0.1
-- The C compiler identification is Clang 12.0.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++-12 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang-12 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sammycage/Projects/lunasvg/build
<font color="#26A269"><b>sammycage@ubuntu</b></font>:<font color="#12488B"><b>~/Projects/lunasvg/build</b></font>$ make -j3
[  3%] <font color="#26A269">Building CXX object CMakeFiles/lunasvg.dir/source/lunasvg.cpp.o</font>
[  9%] <font color="#26A269">Building CXX object CMakeFiles/lunasvg.dir/source/property.cpp.o</font>
[  9%] <font color="#26A269">Building CXX object CMakeFiles/lunasvg.dir/source/element.cpp.o</font>
[ 12%] <font color="#26A269">Building CXX object CMakeFiles/lunasvg.dir/source/parser.cpp.o</font>
[ 15%] <font color="#26A269">Building CXX object CMakeFiles/lunasvg.dir/source/layoutcontext.cpp.o</font>
[ 18%] <font color="#26A269">Building CXX object CMakeFiles/lunasvg.dir/source/canvas.cpp.o</font>
[ 21%] <font color="#26A269">Building CXX object CMakeFiles/lunasvg.dir/source/clippathelement.cpp.o</font>
[ 25%] <font color="#26A269">Building CXX object CMakeFiles/lunasvg.dir/source/defselement.cpp.o</font>
[ 28%] <font color="#26A269">Building CXX object CMakeFiles/lunasvg.dir/source/gelement.cpp.o</font>
[ 31%] <font color="#26A269">Building CXX object CMakeFiles/lunasvg.dir/source/geometryelement.cpp.o</font>
[ 34%] <font color="#26A269">Building CXX object CMakeFiles/lunasvg.dir/source/graphicselement.cpp.o</font>
[ 37%] <font color="#26A269">Building CXX object CMakeFiles/lunasvg.dir/source/maskelement.cpp.o</font>
[ 40%] <font color="#26A269">Building CXX object CMakeFiles/lunasvg.dir/source/markerelement.cpp.o</font>
[ 43%] <font color="#26A269">Building CXX object CMakeFiles/lunasvg.dir/source/paintelement.cpp.o</font>
[ 46%] <font color="#26A269">Building CXX object CMakeFiles/lunasvg.dir/source/stopelement.cpp.o</font>
[ 50%] <font color="#26A269">Building CXX object CMakeFiles/lunasvg.dir/source/styledelement.cpp.o</font>
[ 53%] <font color="#26A269">Building CXX object CMakeFiles/lunasvg.dir/source/styleelement.cpp.o</font>
[ 56%] <font color="#26A269">Building CXX object CMakeFiles/lunasvg.dir/source/svgelement.cpp.o</font>
[ 59%] <font color="#26A269">Building CXX object CMakeFiles/lunasvg.dir/source/symbolelement.cpp.o</font>
[ 62%] <font color="#26A269">Building CXX object CMakeFiles/lunasvg.dir/source/useelement.cpp.o</font>
[ 65%] <font color="#26A269">Building C object CMakeFiles/lunasvg.dir/3rdparty/plutovg/plutovg.c.o</font>
[ 68%] <font color="#26A269">Building C object CMakeFiles/lunasvg.dir/3rdparty/plutovg/plutovg-paint.c.o</font>
[ 71%] <font color="#26A269">Building C object CMakeFiles/lunasvg.dir/3rdparty/plutovg/plutovg-geometry.c.o</font>
[ 75%] <font color="#26A269">Building C object CMakeFiles/lunasvg.dir/3rdparty/plutovg/plutovg-blend.c.o</font>
[ 78%] <font color="#26A269">Building C object CMakeFiles/lunasvg.dir/3rdparty/plutovg/plutovg-rle.c.o</font>
[ 81%] <font color="#26A269">Building C object CMakeFiles/lunasvg.dir/3rdparty/plutovg/plutovg-dash.c.o</font>
[ 84%] <font color="#26A269">Building C object CMakeFiles/lunasvg.dir/3rdparty/plutovg/plutovg-ft-raster.c.o</font>
[ 87%] <font color="#26A269">Building C object CMakeFiles/lunasvg.dir/3rdparty/plutovg/plutovg-ft-stroker.c.o</font>
[ 90%] <font color="#26A269">Building C object CMakeFiles/lunasvg.dir/3rdparty/plutovg/plutovg-ft-math.c.o</font>
[ 93%] <font color="#26A269"><b>Linking CXX shared library liblunasvg.so</b></font>
[ 93%] Built target lunasvg
[ 96%] <font color="#26A269">Building CXX object example/CMakeFiles/svg2png.dir/svg2png.cpp.o</font>
[100%] <font color="#26A269"><b>Linking CXX executable svg2png</b></font>
[100%] Built target svg2png
<font color="#26A269"><b>sammycage@ubuntu</b></font>:<font color="#12488B"><b>~/Projects/lunasvg/build</b></font>$ UBSAN_OPTIONS=halt_on_error=1:print_stacktrace=1 ASAN_OPTIONS=halt_on_error=1 example/svg2png &apos;/home/sammycage/Downloads/e-feMorphology-009.bmfull_rand_base.ts3.e18.s0.sid451.smtbit_opt_uc.svg&apos;
Generated PNG file : e-feMorphology-009.bmfull_rand_base.ts3.e18.s0.sid451.smtbit_opt_uc.svg.png
<font color="#26A269"><b>sammycage@ubuntu</b></font>:<font color="#12488B"><b>~/Projects/lunasvg/build</b></font>$ 

</pre>

**Comment by m-carrasco** [comment]
Hi @sammycage 

I minimized the SVG file I originally reported. This new SVG file is valid, shorter, and triggers the same UB error. You can use `svg2png` as it is in `master` to trigger the UB error.  The steps to reproduce the bug are as follows:

1. Clone: `git clone https://github.com/sammycage/lunasvg.git && cd lunasvg`
2. Build with sanitisers: `mkdir build && cd build && CXX=clang++ CC=clang cmake -DLUNASVG_BUILD_EXAMPLES=ON -DCMAKE_CXX_FLAGS="-g -O0 -fsanitize=undefined,address -fno-sanitize-recover=all" -DCMAKE_C_FLAGS="-g -O0 -fsanitize=undefined,address -fno-sanitize-recover=all" ../  && make -j4`
3. Download minimized svg: `wget -O example.svg https://user-images.githubusercontent.com/3461126/225024410-286b1073-7d19-41b9-8c26-7641abe72579.svg` (it is attached in this post, in case this fails)
4. Run with sanitisers:  `UBSAN_OPTIONS=halt_on_error=1:print_stacktrace=1 ASAN_OPTIONS=halt_on_error=1 ./example/svg2png example.svg`

Minimized SVG file: [example.svg](https://user-images.githubusercontent.com/3461126/225024410-286b1073-7d19-41b9-8c26-7641abe72579.svg)

I hope this test case is more helpful in solving the issue.  Let me know if I can still improve this report, and thanks for sharing this project.

Best regards,
Manuel

**Comment by sammycage** [comment]
Could you please try to reproduce this error with gcc? I'm encountering difficulties with clang.

**Comment by m-carrasco** [comment]
Hi @sammycage 

Thanks for your quick response! 

GCC's sanitiser does not detect the problem, but there is a real issue, as reported by clang: `-nan is outside the range of representable values of type 'int'`.  This kind of problem could cause portability issues or non-deterministic behaviour when optimizations are enabled.

The reported [line](https://github.com/sammycage/lunasvg/blob/585d61eef24510bc0b7fe3d9e768d0675d4b5a6f/3rdparty/plutovg/plutovg-blend.c#L147) by clang is: `int ipos = (int)(pos * (COLOR_TABLE_SIZE - 1) + 0.5);` in the `gradient_pixel` function.

I  checked `isnan(pos * (COLOR_TABLE_SIZE - 1) + 0.5)`  right before the cast, and both compilers confirm that the casted value is a `nan`.

In addition, I checked the raised floating-point exceptions using `fetestexcept(FE_ALL_EXCEPT)`, right before the cast. In both cases, it reports that `FE_INVALID` has been raised. This can be caused by a domain error when using a floating-point function. 

The `nan` and the exception are caused when `gradient_pixel` is [called](https://github.com/sammycage/lunasvg/blob/585d61eef24510bc0b7fe3d9e768d0675d4b5a6f/3rdparty/plutovg/plutovg-blend.c#L264):` *buffer++ = gradient_pixel(gradient, sqrt(det) - b)`.

Using both compilers, I confirmed that `det` is negative zero, thus causing `sqrt` to return a `nan` and raise the exception.

To summarize, the `sqrt` call on a negative value (`det`) returns a `nan`. This `nan` flows into `gradient_pixel`  and causes the UB reported by clang when casted to an integer. 

-------------------------------

I found two possible ways to fix the UB and still correctly render the SVG.

At another [callsite](https://github.com/sammycage/lunasvg/blob/585d61eef24510bc0b7fe3d9e768d0675d4b5a6f/3rdparty/plutovg/plutovg-blend.c#L246) of `gradient_pixel`, `det` signedness is checked before calling `sqrt`:

```
            if(det >= 0)
            {
                double w = sqrt(det) - b;
                if(gradient->radial.fr + v->dr * w >= 0)
                    result = gradient_pixel(gradient, w);
            }
```

I tested this change, which applies the same check, and it seems to work:

```
diff --git a/3rdparty/plutovg/plutovg-blend.c b/3rdparty/plutovg/plutovg-blend.c
index 6cbe76e..ec3925c 100644
--- a/3rdparty/plutovg/plutovg-blend.c
+++ b/3rdparty/plutovg/plutovg-blend.c
@@ -261,7 +261,9 @@ static void fetch_radial_gradient(uint32_t* buffer, const radial_gradient_values
     {
         while(buffer < end)
         {
-            *buffer++ = gradient_pixel(gradient, sqrt(det) - b);
+            if (det >= 0)
+                *buffer = gradient_pixel(gradient, sqrt(det) - b);
+            buffer++;
             det += delta_det;
             delta_det += delta_delta_det;
             b += delta_b;
```

Alternatively, I tested `*buffer++ = gradient_pixel(gradient, sqrt(fabs(det)) - b)` and it also seems to work. The fix computes the absolute value of `det`, which can be negative zero sometimes, before calling `sqrt`.

```
diff --git a/3rdparty/plutovg/plutovg-blend.c b/3rdparty/plutovg/plutovg-blend.c
index 6cbe76e..ea08d40 100644
--- a/3rdparty/plutovg/plutovg-blend.c
+++ b/3rdparty/plutovg/plutovg-blend.c
@@ -261,7 +261,7 @@ static void fetch_radial_gradient(uint32_t* buffer, const radial_gradient_values
     {
         while(buffer < end)
         {
-            *buffer++ = gradient_pixel(gradient, sqrt(det) - b);
+            *buffer++ = gradient_pixel(gradient, sqrt(fabs(det)) - b);
             det += delta_det;
             delta_det += delta_delta_det;
             b += delta_b;
```

Let me know if there is anything else I can do. I can also open a pull request if any of the fixes look good to you. 

Best regards,
Manuel.

**Comment by sammycage** [comment]
> Let me know if there is anything else I can do. I can also open a pull request if any of the fixes look good to you.

```cpp
        while(buffer < end)
        {
            uint32_t result = 0; // .
            if(det >= 0)
                result = gradient_pixel(gradient, sqrt(det) - b);
            *buffer++ = result;
            det += delta_det;
            delta_det += delta_delta_det;
            b += delta_b;
        }
```

**Comment by m-carrasco** [comment]
@sammycage I appreciate your quick response. I opened a [PR](https://github.com/sammycage/lunasvg/pull/123) for this fix.

> Just being curious, what are you using this library for?

 We are using it as a benchmark for a fuzzing research project. Thanks for sharing LunaSVG o/

**Comment by sammycage** [comment]
Thanks for your findings, this especially https://github.com/sammycage/lunasvg/issues/119
