### ISSUE TITLE
Rendering issue (mismatch with other SVG libraries)

### ISSUE THREAD

**Issue by m-carrasco** [sammycage/lunasvg#127]
Hi,

I found this [SVG file](https://user-images.githubusercontent.com/3461126/227211712-b2e7567a-61e8-4111-a390-4dda417f9b5d.svg) causing LunaSVG (b66e22402526ae2fc58a0de508442401002b550b) to generate a different image to GNOME Image Viewer (v3.36.3), ReSVG (v0.29.0), and Firefox (v111.0).

[LunaSVG PNG](https://user-images.githubusercontent.com/3461126/227212075-ec116f79-a01f-47aa-88ba-947379b34173.png)

The PNG generated by LunaSVG mismatches in drawing the two-ends tail of the triangle, at the top left side of the image. The next image is a side by side comparison of LunaSVG (top) and Image Viewer (bottom), and the mismatch region in red (added by me):

![mismatch](https://user-images.githubusercontent.com/3461126/227214057-ea0b38a9-331d-4022-a57a-0fbffcfef9ed.png)

If possible, I'd like to ask/confirm if this is a bug in LunaSVG or it is a legal difference between the SVG libraries. 

Thanks for sharing this project o/

Best regards,
Manuel

**Comment by m-carrasco** [comment]
Hi Sam,

Thanks a lot for checking on this bug!

> I am reaching out to request the original source site for the file that you provided. I am currently working on fixing a code bug and I believe that the information on the original source site may be necessary for me to successfully resolve the issue.

The reported SVG file was generated by us in the context of our research. I am not sure if I understand what you mean by source site. Could you tell me what information in specific would be helpful to solve the bug?

Best regards,
Manuel.

**Comment by sammycage** [comment]
Could you please provide an explanation of the purpose of this file in relation to bug testing?

For instance, this [file](https://github.com/RazrFalcon/resvg/blob/master/tests/svg/a-stroke-linecap-004.svg?short_path=f9963a9) was created to be used for testing the behavior of the round line-cap when applied to paths with zero length? #40

**Comment by m-carrasco** [comment]
Hi Sam,

I can't provide a particular use case for the given input since the SVG has been generated in an automated way. We understand that the SVG specification determines the semantics of the test case and the expected behaviour is validated by checking the result with different SVG libraries (as reported). 

Our research goal is to automatically generate a valid SVG for LunaSVG, which exhibits a rendering bug. The technique analyzes LunaSVG and ensures generating an SVG that LunaSVG accepts. Then, we classify it as a bug when there is a divergence with several other SVG rendering libraries. 

Thanks again for your time!

Best regards,
Manuel.
