### ISSUE TITLE
Feature request: embedded bitmap

### ISSUE THREAD

**Issue by vitekcerny** [sammycage/lunasvg#13]
Hi, I’m looking for a way to display shadows using lunasvg. I know that svg filters (like gaussian blur) are not implemented. Is there any chance for embedded images support, so I can use shadows like this example?
[example.zip](https://github.com/sammycage/lunasvg/files/5519000/example.zip)

**Comment by sammycage** [comment]
SVG FILTERS IS NOW MY NUMBER ONE PRIORITY.

**Comment by vitekcerny** [comment]
Thank you, that would be great. Good luck with that.

**Comment by fire** [comment]
How can I help?
