### ISSUE TITLE
Binary size

### ISSUE THREAD

**Issue by mgord9518** [sammycage/lunasvg#130]
Hello, I'm interested in possibly using this library to make a KVantum engine for Zig FLTK bindings as nanosvg (which FLTK uses by default) is quite slow and eats up too many resources when doing redraws.

Roughly how big is the size impact when building a binary with this library? 500kB is probably the maximum that would work for my use case

**Comment by g40** [comment]
Suggest you try it out as there are a large number of options in play when you build. Including OS, compiler, etc.

Just to give you a clue: VS2022 static release build of svg2png shows these numbers:

`R:\src\libs\lunasvg\build\Release\svg2png.exe 557,056 bytes 2023/6/28-21:20:40`
