### ISSUE TITLE
Is this a rendering bug?

### ISSUE THREAD

**Issue by 9844201** [sammycage/lunasvg#139]
![openssl](https://github.com/sammycage/lunasvg/assets/3508145/3d390d7d-945e-4ba8-83ed-c6fed4388eb6)
[openssl.svg.zip](https://github.com/sammycage/lunasvg/files/12658726/openssl.svg.zip)

Unable to parse openssl.svg normally
![render](https://github.com/sammycage/lunasvg/assets/3508145/f9ad2084-dfc7-4bf3-bc9c-11e489a175df)

**Comment by ivantishchenko** [comment]
The SVG you attached contains the text tags in the XML.

According to the documentation text is to be implemented:
https://github.com/sammycage/lunasvg/blob/9a05e196382ebe4ef7993039d069ab6312b60fac/README.md?plain=1#L45

The other SVGs you attached contain the xlink:href tag, which probably are also not implemented yet.

**Comment by ivantishchenko** [comment]
The SVG you attached contains the text tags in the XML.

According to the documentation text is to be implemented:
https://github.com/sammycage/lunasvg/blob/9a05e196382ebe4ef7993039d069ab6312b60fac/README.md?plain=1#L45

The other SVGs you attached contain the xlink:href tag, which probably are also not implemented yet.

**Comment by ivantishchenko** [comment]
Is a special case of https://github.com/sammycage/lunasvg/issues/113
Will be fixed once image support is implemented.

**Comment by sammycage** [comment]
Thank you for pointing that out! Text, tspan, and image elements are now supported. 

![openssl svg](https://github.com/user-attachments/assets/a34e68e7-8f92-4259-98ee-279d0d7ca577)
