### ISSUE TITLE
Feature : stroke-dasharray

### ISSUE THREAD

**Issue by bcomb** [sammycage/lunasvg#14]
Hi the rasterizer is pretty good but lack of StrokeDash array support.
Do you plan to implement this feature in near future?

SpecRef: https://www.w3.org/TR/SVG11/painting.html#StrokeDasharrayProperty

Here the kind of SVG we generate, and the result we obtain (i use roboto-regular.ttf)

```xml
<svg xmlns="http://www.w3.org/2000/svg" version="1.2" baseProfile="tiny" width="43.95" height="43.95" viewBox="26.75 26.75 146.5 146.5">
<path d="M63,63 C63,20 137,20 137,63 C180,63 180,137 137,137 C137,180 63,180 63,137 C20,137 20,63 63,63 Z" stroke-width="4" stroke-dasharray="8,12" stroke="black" fill="rgb(255, 255, 128)" ></path>
<path d="M50,65L150,135M50,135L150,65" stroke-width="4" stroke="black" fill="black" ></path>
<text x="100" y="77" text-anchor="middle" font-size="30" font-family="Arial"  font-weight="bold" stroke-width="4" stroke="black" fill="black" >R</text>
<path d="M75,140 C75,125 100,125 100,140 C100,125 125,125 125,140" stroke-width="4" stroke="black" fill="none" ></path>
</svg>
```

![test_0312](https://user-images.githubusercontent.com/4551132/98942171-e99a8880-24ed-11eb-8c44-68f84f79b8b2.png)

**Comment by sammycage** [comment]
Yes stroke-dasharray is very much on the roadmap.

**Comment by bcomb** [comment]
I've something working with dasharray, i will submit you something soon, just need a bit of cleaning

**Comment by sammycage** [comment]
Interesting.. Didn't keep me waiting :-)

**Comment by sammycage** [comment]
Thank you... I will take a deep look at it.
