### ISSUE TITLE
Taking Pull requests? SVG2ICO example.

### ISSUE THREAD

**Issue by g40** [sammycage/lunasvg#151]
Hello @sammycage .

I have some relatively simple C++ code here that converts an SVG into a multiple resolution .ICO complete with transparency. It is Windows only. Would you like a PR? (Single C++ .h file only)

```
//-----------------------------------------------------------------------------
// create an icon with 1+ entries from an SVG file
// 256x256 maximum supported size. 32bpp only
static
bool
MakeIcon(
	// .svg filename
	const std::string& ipname,
	// .ico filename
	const std::string& opname,
	// add size pairs to suit
	const std::vector<std::pair<int, int>> dimensions = { {128,128} },
	// transparent background
	std::uint32_t bgColor = 0x00000000)
```
Example output viewed in Axialis Icon Workshop

![image](https://github.com/sammycage/lunasvg/assets/812250/a2cff317-c592-46ac-8e7e-98925aac1974)

**Comment by sammycage** [comment]
Thanks a bunch for your fantastic work! Just a quick note about the pull request: currently, we can't accept requests with dependencies. Hope you understand.

**Comment by g40** [comment]
Hello. I do indeed.

```
#pragma once

#include <string>
#include <iostream>
#include <fstream>
#include <vector>
#include <lunasvg.h>
#includee <windows.h>
```

**Comment by sammycage** [comment]
"#include <windows.h>" is not available on all platforms.

**Comment by g40** [comment]
Err, yes. " It is Windows only."

**Comment by sammycage** [comment]
Okay, create the pull request, and make sure you include a build script. Let me review it.

**Comment by sammycage** [comment]
@g40 FYI, when I say dependencies, I don't solely mean 3rd party libraries; I'm also referring to platforms. A lot of people are using this library because it's standalone.

**Comment by g40** [comment]
PR is available now.
