### ISSUE TITLE
Is there chance that c6cad06 checking is braking the library

### ISSUE THREAD

**Issue by gabrielaexile** [sammycage/lunasvg#156]
Is there chance that c6cad06 checking is braking the library ?

I basically feed matrix to it like this:

lunasvg::Matrix matrix(width / me->Document->width(), 0, 0, height / me->Document->height(), 0, 0)

And render with this:

me->Document->render(bitmap, matrix);

But as of c6cad06 then nothing gets drawn.

**Comment by sammycage** [comment]
Thanks for your feedback. I am currently investigating the issue and will keep you updated on any progress.

**Comment by sammycage** [comment]
@gabrielaexile To help us investigate and address the problem more effectively, could you please provide a test file or sample data that reproduces the issue?

**Comment by gabrielaexile** [comment]
I was basically just using the tiger.svg.  Am guessing you did not manage to reproduce the problem ?

And setting matrix before calling render so something like:

int height = 500;
int width = 500;

// Buffer for the image is created before this.

auto document = Document::loadFromFile("tiger.svg");

auto bitmap = lunasvg::Bitmap(buffer, width, height, width * 4);

if (!bitmap.valid())
{
    return NULL;
}

bitmap.clear(bgColor);

lunasvg::Matrix matrix(width / document ->width(), 0, 0, height / document ->height(), 0, 0);
document ->render(bitmap, matrix);

**Comment by sammycage** [comment]
@gabrielaexile Could you please also share the "tiger.svg" file that you mentioned?

**Comment by wisebjorne** [comment]
![Tiger](https://github.com/sammycage/lunasvg/assets/157806863/105a4f7e-570f-44fe-8bf2-4f6639690512)

Here it is, (sorry I thought this file was from you since your example mentions tiger.svg)

**Comment by gabrielaexile** [comment]
![Tiger](https://github.com/sammycage/lunasvg/assets/73896333/25c416e7-1b4d-43fd-b27d-fe6a37d3484e)

**Comment by gabrielaexile** [comment]
I started again with clean repo and got it to work finally. So closing this (sorry about the false alarm) !!

**Comment by gabrielaexile** [comment]
got it to work
