### ISSUE TITLE
Local transformation and internal SVG element access - Text object attributes

### ISSUE THREAD

**Issue by rossanoparis** [sammycage/lunasvg#165]
### Data
This issue refers to: [issue 98](https://github.com/sammycage/lunasvg/issues/98)
Library version: v2.3.9 (master)
Testing SVG file: [groups.svg.zip](https://github.com/sammycage/lunasvg/files/14958440/groups.svg.zip) (InkScape)

| Document    | Details |
| -------- | ------- |
| ![image](https://github.com/sammycage/lunasvg/assets/33904565/f1bfcceb-fd9c-4d55-83b0-3aaba5dc8125) | **IDs text2, text3**<br> ![image](https://github.com/sammycage/lunasvg/assets/33904565/dcff51f1-1cb6-40d1-a8e0-29eebd05a94b)|

### Scope
For a "text object" I'd like to get the following attributes: text value (array of strings), text position (array of float) and text angle
Because they are useful to draw texts using other functions from other libraries ( for instance, wxWidgets )
It is up to the user select an appropriate font to draw them.

### Testing code
```
// Load document
auto document = Document::loadFromFile(filesvg);
Box dbox(0, 0, document->width(), document->height());

// Retrieve the SVG element - text2
auto text2 = document->getElementById("text2");
```
### Results
The pointer returned by the function `auto text2 = document->getElementById("text2");` returns a NULL pointer.

### Remarks
It is known that LunaSVG doesn't handle texts; they can't be rendered.
Any way, it could handle them as internal objects with the scope of being useful for a user who needs to get their attributes.
Perhaps LunaSVG should own functions able to operate on text objects only, in order to get something like below

**ID text2**
Text value[0] = TEXT2
Text position X[0] = 12.732866
Text position Y[0] = 141.75731
Text angle = -40.234662

**ID text3**
Text value[0] = TEXT3.1
Text value[1] = TEXT3.2
Text position X[0] = 73.865891
Text position Y[0] = 103.12551
Text position X[1] = 73.865891
Text position Y[2] = 108.12551
Text angle = 0

**Comment by sammycage** [comment]
@rossanoparis The text element is now supported in LunaSVG. Here's an example demonstrating the retrieval and display of text element positions and sizes:

```cpp
auto document = Document::loadFromFile("groups.svg");
auto element1 = document->getElementById("text1");
auto element2 = document->getElementById("text2");
auto element3 = document->getElementById("text3");

// Retrieve the global bounding box (position and size) of each element
auto bbox1 = element1.getGlobalBoundingBox();
auto bbox2 = element2.getGlobalBoundingBox();
auto bbox3 = element3.getGlobalBoundingBox();

// Display the position and size (x, y, width, height) of each element
std::cout << "Text 1 is located at ("
          << bbox1.x << ", " << bbox1.y
          << ") with a size of (" << bbox1.w
          << " x " << bbox1.h << ")" << std::endl;
std::cout << "Text 2 is located at ("
          << bbox2.x << ", " << bbox2.y
          << ") with a size of (" << bbox2.w
          << " x " << bbox2.h << ")" << std::endl;
std::cout << "Text 3 is located at ("
          << bbox3.x << ", " << bbox3.y
          << ") with a size of (" << bbox3.w
          << " x " << bbox3.h << ")" << std::endl;
```

Output:

> Text 1 is located at (0.644348, 115.662) with a size of (32.7282 x 12)  
> Text 2 is located at (95.6209, 120.299) with a size of (32.7359 x 30.3007)  
> Text 3 is located at (19.5467, 148.569) with a size of (42.5638 x 27)

---

This should clarify that LunaSVG can now handle and render text elements effectively!
