### ISSUE TITLE
Objects with gradients are shown differently

### ISSUE THREAD

**Issue by rossanoparis** [sammycage/lunasvg#169]
The conversion from this SVG file to a PNG image, shows badly two objects with gradients
[velocimetro.zip](https://github.com/sammycage/lunasvg/files/15417951/velocimetro.zip)

The white gradient above the green arrows and the gray shadow are shown differently.

![image](https://github.com/sammycage/lunasvg/assets/33904565/00312a05-20c0-4ffb-8a44-ec48ce3af37f)

**Comment by sammycage** [comment]
The issue you're experiencing with the gradients in the SVG to PNG conversion is due to the use of filters. Unfortunately, filters are not currently supported, which is causing the discrepancies you're seeing with the white gradient above the green arrows and the gray shadow.

**Comment by rossanoparis** [comment]
Thank you @sammycage 
I'm sorry, I forgot the 'TODO' list that details the library.
