### ISSUE TITLE
how to get the library version information

### ISSUE THREAD

**Issue by rossanoparis** [sammycage/lunasvg#172]
Perhaps I didn't look carefully, but I was not able to find a way to to get the library version information from source code.

**Comment by sammycage** [comment]
#45 #170

**Comment by sammycage** [comment]
This feature has been added in the latest commit. Here's a concise example demonstrating the use of both `LUNASVG_VERSION_STRING` and `LUNASVG_VERSION_ENCODE`:

```cpp
#include <iostream>
#include <lunasvg.h>

int main() {
    std::cout << "LunaSVG version: " << LUNASVG_VERSION_STRING << std::endl;
    if (LUNASVG_VERSION > LUNASVG_VERSION_ENCODE(2, 3, 0)) {
        std::cout << "Current version is newer than 2.3.0" << std::endl;
    }
    return 0;
}
```
