### ISSUE TITLE
rgba parse failed

### ISSUE THREAD

**Issue by codingBobo** [sammycage/lunasvg#175]
[v2_ic_jjgz.svg.zip](https://github.com/user-attachments/files/16495107/v2_ic_jjgz.svg.zip)

**Comment by sammycage** [comment]
Hey @codingBobo, what's up? What's the issue?

**Comment by codingBobo** [comment]
<rect id="_rect" data-name="rect" class="cls-1" width="90" height="90"></rect>

**Comment by codingBobo** [comment]
> [v2_ic_jjgz.svg.zip](https://github.com/user-attachments/files/16495107/v2_ic_jjgz.svg.zip)

use this link

**Comment by codingBobo** [comment]
ok  It's our own problem, I'll handle it locally first, thanks.
in parser.cpp
`
    if(Utils::skipDesc(ptr, end, "rgba(")) {
        uint8_t r, g, b, a;
        if(!Utils::skipWs(ptr, end)
           || !parseColorComponent(ptr, end, r)
           || !Utils::skipWsComma(ptr, end)
           || !parseColorComponent(ptr, end, g)
           || !Utils::skipWsComma(ptr, end)
           || !parseColorComponent(ptr, end, b)
           || !Utils::skipWsComma(ptr, end)
           || !parseColorComponent(ptr, end, a)
           || !Utils::skipWs(ptr, end)
           || !Utils::skipDesc(ptr, end, ')')) {
            return defaultValue;
        }

        return Color(r, g, b, a);
    }
`

**Comment by sammycage** [comment]
Hi @codingBobo ,

Thank you for pointing this out. Just to let you know, SVG 2 color syntax is now supported in the latest update.

Best regards, 
Samuel
