### ISSUE TITLE
Run on linux

### ISSUE THREAD

**Issue by OriBibi** [sammycage/lunasvg#18]
Does the library have the ability to run on LINUX? If yes, is it possible to get a CMakeLists.txt file to help me with this? Or another guide about how to work with the  library on LINUX .

**Comment by sammycage** [comment]
clone, build and install lunasvg by using this follow commands

```
git clone http://github.com/sammycage/lunasvg.git
cd lunasvg
mkdir build
cd build
make -j 2
make install
```
Then download, extract and build this [lunasvg-example.zip](https://github.com/sammycage/lunasvg/files/5638198/lunasvg-example.zip)

**Comment by OriBibi** [comment]
So, your answer is yes. I gess that in the case of your library it the same way to install on WIndows and Linux (i mean, same CMakeLists.txt) . Am i worng?
Thanks for the quick reply!
