### ISSUE TITLE
Is there a way to change the text of a <text> or <tspan> node?

### ISSUE THREAD

**Issue by bitgenerator** [sammycage/lunasvg#180]
Is there a way to change the text of a text or tspan node, like the attributes?

**Comment by sammycage** [comment]
Currently, no.

**Comment by sammycage** [comment]
@bitgenerator Text nodes manipulation has been added in the latest commit. Here's an example:

```cpp
auto data = R"SVG(<svg xmlns="http://www.w3.org/2000/svg">
<text id='a' y='120' font-size='120'> Hello World</text>
</svg>)SVG";

auto document = Document::loadFromData(data);

auto text_element = document->getElementById("a");
auto text_node = text_element.children().front().toTextNode();
text_node.setData("I love SVG!!!");

document->updateLayout();
```

This should help you modify the text content as needed.

**Comment by bitgenerator** [comment]
Thanks a lot! I've written a similar function but it's good to have a official change. ;-)

**Comment by asmwarrior** [comment]
Hi, can you put the above mentioned code to some official document? For example, the root [README.md](https://github.com/sammycage/lunasvg/blob/master/README.md) file.

As the lunasvg is a "SVG rendering and manipulation library in C++", this is a standard way of "manipulate" the elements of a svg file.

Thanks.

**Comment by sammycage** [comment]
@asmwarrior I'll look into adding this to the README. Appreciate your input!
