### ISSUE TITLE
Serialize the loaded SVG back to a string

### ISSUE THREAD

**Issue by Karandra** [sammycage/lunasvg#184]
Is there a way to save the loaded SVG document to an xml string? There was a function `SVGDocument::toString` in the older versions, in 1.4.x at least. Now there isn't one. I'm thinking maybe it's possible to reconstruct the file traversing the document through its root element, but I'd rather use something that's already there, if possible.

**Comment by sammycage** [comment]
`SVGDocument::toString` is not coming back for the sake of simplicity, and currently, reconstructing the document by traversing it through the root element isn't possible either.

**Comment by Karandra** [comment]
That is not fun. Guess I'll have to find a different SVG library, because I need this feature. Or I can stick to v1.4.

**Comment by Karandra** [comment]
Is that function available in 1.4 and is public?

**Comment by sammycage** [comment]
No, that function isn't available in 1.4 and isn't public. Also, v1.4.x is quite old, so I wouldn’t recommend sticking with it.
