### ISSUE TITLE
Unresolved external symbol

### ISSUE THREAD

**Issue by goliat26** [sammycage/lunasvg#185]
I have problem with building and importing lib to any of my project even new clear test project.

I clone repo then build by cmake or visual studio (i tried both methods).
I setup project Additional Include Directories with "include" directory in repository and Additional Library Directories with directory when i build .lib file.

For test i just add auto document = lunasvg::Document::loadFromData(resource.Blocks.at(0)->Data); code then try rebuild and i always get Unresolved external symbol error. I tried also dumpbin.exe /EXPORTS and there are no functions exported in this lib.

Are they any additional build parameters required or something else?

**Comment by sammycage** [comment]
Since you are building a static library on Windows, define `LUNASVG_BUILD_STATIC` before importing the library.

**Comment by goliat26** [comment]
> Since you are building a static library on Windows, define `LUNASVG_BUILD_STATIC` before importing the library.

You save my life with this simple reply :).
Thanks for that.
