### ISSUE TITLE
If font-famliy has single quotes, the font family is not working.

### ISSUE THREAD

**Issue by bitgenerator** [sammycage/lunasvg#186]
If **Comic Sans MS** is added via **lunasvg_add_font_face_from_data** as **"Comic Sans MS"** and an editor like InkScape is refering to this font in style as **font-family:'Comic Sans MS'**, the font is not rendered. I need to add the font as  **"'Comic Sans MS'"** to the function. So, somehow single quotes parsing is missing,

**Comment by sammycage** [comment]
Thanks for pointing this out! I’ve fixed the issue by adding support for font-family names with quotes. `lunasvg_add_font_face_from_data` should now handle fonts like `'Comic Sans MS'` correctly. Let me know if it works for you!

**Comment by bitgenerator** [comment]
Looks good :-) Thanks a lot!
