### ISSUE TITLE
<Image> started to tile when rendering to bitmap larger than SVG's dimensions

### ISSUE THREAD

**Issue by lamweilun** [sammycage/lunasvg#187]
I have a SVG file of dimensions 414x896, internally it has a raw image, with the `<Image>` tag with the dimension 900x1200. When I invoked `renderToBitmap` with a width and height that's 3x of the SVG dimensions, the internal `<Image>` started to tile. Is this an intended behaviour? Is it possible to control its wrapping mode? I am on the latest 3.0.0 version

**Comment by sammycage** [comment]
Could you please share the SVG file you're working with? That would help me get a better understanding of what's going on internally and why the image is behaving this way. I'd like to see how it's structured and where the issue might be coming from.

**Comment by lamweilun** [comment]
![Foot](https://github.com/user-attachments/assets/4e199ac1-2df8-471d-9050-480d4badecf6)

Here's another file. The SVG dimension is 353x233, the `<Image>` internally is 299x360.

Here's the rough code:
```C++
std::vector<unsigned char> rawRGBA;
std::unique_ptr<Document> doc = Document::loadFromData(rawFileData);
if (doc)
{
  const int scale = 7;
  const int scaledWidth = doc->width() * scale;
  const int scaledHeight = doc->height() * scale;
  auto bitmap = doc->renderToBitmap(scaledWidth, scaledHeight, 0x00000000);
  if (!bitmap.isNull())
  {
    bitmap.convertToRGBA();
    rawRGBA = std::vector<u8>(bitmap.data(), bitmap.data() + (bitmap.width() * bitmap.height() * 4));
  }
}
```

My end-goal is to get the internal RGBA data of an upscaled version of a specific SVG file. For this file, I have tested that at an upscale of 7, the internal `<Image>` begins to tile. Resulting in it looking like this.

![image](https://github.com/user-attachments/assets/e46c3125-207e-4182-9417-f5889f0faeea)

**Comment by sammycage** [comment]
> I am not exactly sure if there's a better way to send images as a file on Github, let me know if you need the original file through other means

No worries! The issue has been properly replicated on my end. I'm currently working on it and will keep you updated.

**Comment by sammycage** [comment]
I’ve finally managed to fix the bug! 

Thank you so much for bringing this to my attention—your detailed report was invaluable in helping me get to the bottom of it. I really appreciate your input.

Please update to the [latest commit of plutovg](https://github.com/sammycage/plutovg/commit/a24c3007be5754a0dca11a4502bdadddca1c009e), and let me know if everything works smoothly on your end!
