### ISSUE TITLE
Question about Document::matrix() removal

### ISSUE THREAD

**Issue by Randalphwa** [sammycage/lunasvg#191]
I have a couple of different ways that I was converting a Document rendered bitmap into a wxBitmap for use by wxWidgets. In 3.0, one of those no longer compiles. Previously, I was doing this:

```C++
    const auto scale = wxMin(size.x / document->width(), size.y / document->height());
    const auto documentMatrix = document->matrix();
    const auto scaleMatrix = documentMatrix.scaled(scale, scale);
    Bitmap lbmp(size.x, size.y);

    lbmp.clear(0);
    document->render(lbmp, scaleMatrix);
```

after which I could convert lbmp into a wxWidgets wxBitmap.

However, the 3.0 release removes the `matrix()` method from the `Document` class:

```C++

    /**
     * @brief Returns the current transformation matrix of the document
     * @return the current transformation matrix
     */
    Matrix matrix() const;


Matrix Document::matrix() const
{
    if(m_rootBox == nullptr)
        return Matrix();
    return m_rootBox->transform;
}

private:
    ...
    std::unique_ptr<LayoutSymbol> m_rootBox;
```

Before I go into experimenting mode trying to find another way to do this, I wanted to see if this is simply a matter of creating an instance of Matrix() as if the no longer existing m_rootBox would always be a nullptr?

**Comment by sammycage** [comment]
@Randalphwa Since `Matrix::scaled` is a static method, you can use it directly, making the call to `document->matrix().scaled` redundant. You can simplify your code like this:

```c++
const auto scale = wxMin(size.x / document->width(), size.y / document->height());
const auto scaleMatrix = Matrix::scaled(scale, scale);
Bitmap lbmp(size.x, size.y);

lbmp.clear(0);
document->render(lbmp, scaleMatrix);
```

**Comment by Randalphwa** [comment]
Thanks! Is there any particular advantage to rendering using the Matrix::scale() with `document->render(lbmp, scaleMatrix);` versus just calling `const Bitmap lbmp = document->renderToBitmap(size.x, size.y);`?

**Comment by sammycage** [comment]
Thank you for the question! `Document::renderToBitmap` is actually an overload of `Document::render`. When you call `Document::renderToBitmap`, it internally calls `Document::render` with the appropriate scale. If you need to apply a custom transformation matrix—like a rotation, skew, or non-uniform scale—then `Document::render` is designed to accommodate those types of operations.


https://github.com/sammycage/lunasvg/issues/96#issuecomment-1220314547

**Comment by Randalphwa** [comment]
Excellent -- that explanation helps a lot, and in particular allows me to simplify the calling code.
