### ISSUE TITLE
Problem with tweak-more.svg file

### ISSUE THREAD

**Issue by Randalphwa** [sammycage/lunasvg#192]
Screenshot comparison:

![tweak-more](https://github.com/user-attachments/assets/98ce1f97-2594-480d-addb-e3abb4f61df1)

SVG file:

![tweak-more](https://github.com/user-attachments/assets/e54fa81a-f806-4c67-978e-1c3bf4b8d128)

**Comment by sammycage** [comment]
Maybe the pixelation is due to an incorrect scale setting when rendering with `svg2png hello.svg 40x40`. I don't notice any difference in output quality. Can you please share your code?

![hello svg](https://github.com/user-attachments/assets/025759cf-3243-4441-912c-8766fbea4edd)

**Comment by Randalphwa** [comment]
Same issue (i.e., user error, mea culpa, etc.) as #193. 😢
