### ISSUE TITLE
Feature Request: Update only a part of the SVG

### ISSUE THREAD

**Issue by bitgenerator** [sammycage/lunasvg#194]
Hi,

is there any way to draw only a part the SVG into an existing image, e.g. after update of a text?

I've played around a bit:
- Using render method of the element and pasting this image into the previous rendered full image is working but the aliasing or positions that have a fractional part cause that the update "jumps" a bit. The Element::renderToBitmap method needs an upate for this, using floats for the calculation gives better results....but it does not completely prevent the effect.
- Implement a updateLayout function for elements: My assumption was if the state in the element is invalid, the library would only draw this part of the SVG. It draws the full SVG, so no optimization.

Is there maybe another way where I can have a look?

Best Mario

**Comment by sammycage** [comment]
Hi Mario,

The `Document::updateLayout` function currently validates the whole document, though I may work on optimizing this in the future to validate only the specific elements that were updated.

Regarding the positioning issues you mentioned, could you please share some example code or an illustration? This would help me better understand the aliasing or positioning effects you're experiencing.

**Comment by bitgenerator** [comment]
Yes, lets have a look on a simple example, a rectangle which position is at x=218.5 y=187:

` <svg width="800" height="600" xmlns="http://www.w3.org/2000/svg">

 <g>
  <title>Layer 1</title>
  <rect id="svg_1" height="65" width="338" y="187" x="218.5" stroke="#000" fill="#fff"/>
  <text xml:space="preserve" text-anchor="start" font-family="Noto Sans JP" font-size="24" id="svg_2" y="225" x="330.5" stroke-width="0" stroke="#000" fill="#000000">Test Test</text>
 </g>
</svg>`

![grafik](https://github.com/user-attachments/assets/26ddd4b4-3788-43c7-b245-6f4f688fe903)

If i measure the top left corner, the rectangle is drawn as document at 218x187, the line is 1px and dark. When I render the rect with the renderToBitmap from the Element class, the output differs:

![grafik](https://github.com/user-attachments/assets/b6d21db7-7fa4-403f-89b1-1ea54b150070)

The left line of the rect is 2px and grey, getGlobalBoundingBox gives x=216.5 y=185 to draw the element.

**Comment by sammycage** [comment]
I understand what you are trying to do. The issue here is that achieving this can only be done effectively within the library itself, using techniques like dirty rectangles and clipping.
