### ISSUE TITLE
Replacement for setMatrix?

### ISSUE THREAD

**Issue by hmaarrfk** [sammycage/lunasvg#198]
Hello,

I'm trying to use lunasvg with hello_imgui and it seems that setMatrix got changed between 2.X and 3.0.

If code l have code that looks like:

```
    state->svg->setMatrix(state->svg->matrix().identity()); // Reset the svg matrix to the default value
    state->svg->render(bitmap, state->matrix);              // state->matrix is already scaled and translated
```

https://github.com/ocornut/imgui/blob/ee2119d7cbe1361689f9a7a6ef6853c1deae08f6/misc/freetype/imgui_freetype.cpp#L883

what would the correct migration path look like?

Thanks for your help!

Best,

Mark

**Comment by sammycage** [comment]
Hey Mark,

Check out this comment here: https://github.com/sammycage/lunasvg/issues/150#issuecomment-2381364213 — it might have what you need to handle the migration.

Cheers!

**Comment by hmaarrfk** [comment]
Thanks pthom actually seems to have fixed it in a branch but hasn't merged it yet. 

Thanks for your fast response!!!
