### ISSUE TITLE
Some SVG is not supported,like this.

### ISSUE THREAD

**Issue by chengang151** [sammycage/lunasvg#2]
[nonsupport.zip](https://github.com/sammycage/lunasvg/files/4929036/nonsupport.zip)
Some SVG is not supported,like this.

**Comment by chengang151** [comment]
Can you directly support RGBA!

**Comment by chengang151** [comment]
int color = 0;                
               uint8_t a = (color & 0x000000FF);
                uint8_t r = (color & 0x0000FF00) >>8;
                uint8_t g = (color & 0x00FF0000) >> 16;
                uint8_t b = (color & 0xFF000000) >> 24;

                float aa = (float)a;
               // float value = aa / 255f;
                r /= a;
                g /= a;
                b /= a;
                r *= 255;
                g *= 255;
                b *= 255;

                color = 0;
                color |= a;

                color <<= 8;
                color |= r;
                color <<= 8;

                color |= g;
                color <<= 8;

                color |= b;
The picture is always wrong.

**Comment by sammycage** [comment]
DOCTYPE tag is not support for now. The bitmap is the same as cairo. Thanks for your feedback.

**Comment by sammycage** [comment]
convert bitmap to RGBA
```cpp
void argbTorgba(Bitmap bitmap)
{
    std::uint8_t* ptr = bitmap.data();
    std::uint8_t* end = ptr + bitmap.height() * bitmap.width() * 4;
    while(ptr < end)
    {
#if __BYTE_ORDER == __LITTLE_ENDIAN
        std::uint8_t a = ptr[0];
        std::uint8_t r = ptr[1];
        std::uint8_t g = ptr[2];
        std::uint8_t b = ptr[3];
#else
        std::uint8_t a = ptr[3];
        std::uint8_t r = ptr[2];
        std::uint8_t g = ptr[1];
        std::uint8_t b = ptr[0];
#endif
        if(a != 0)
        {

            ptr[0] = (r * 255) / a;
            ptr[1] = (g * 255) / a;
            ptr[2] = (b * 255) / a;
            ptr[3] = a;
        }
        else
        {
            ptr[0] = 0;
            ptr[1] = 0;
            ptr[2] = 0;
            ptr[3] = 0;
        }

        ptr += 4;
    }
}

```

**Comment by sammycage** [comment]
Doctype tag will be added soon. Please remove <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"> from the svg files.

**Comment by chengang151** [comment]
Hello, the SVG image is displayed incorrectly. Have you tested android?
![微信图片_20200718093053](https://user-images.githubusercontent.com/38270311/87841648-7d11d300-c8d9-11ea-9c34-d21f2252e0f6.jpg)The image on the left is normal, and lunasvg is on the right。

**Comment by sammycage** [comment]
I made a mistake on my previous comment. Please note that ARM CPU are mostly Little endian.
```cpp
void argbTorgba(Bitmap bitmap)
{
    std::uint8_t* ptr = bitmap.data();
    std::uint8_t* end = ptr + bitmap.height() * bitmap.width() * 4;
    while(ptr < end)
    {
#if __BYTE_ORDER == __LITTLE_ENDIAN
        std::uint8_t b = ptr[0];
        std::uint8_t g = ptr[1];
        std::uint8_t r = ptr[2];
        std::uint8_t a = ptr[3];
#else
        std::uint8_t a = ptr[0];
        std::uint8_t r = ptr[1];
        std::uint8_t g = ptr[2];
        std::uint8_t b = ptr[3];
#endif
        if(a != 0)
        {
            // un premultiply alpha
            ptr[0] = (r * 255) / a;
            ptr[1] = (g * 255) / a;
            ptr[2] = (b * 255) / a;
            ptr[3] = a;
        }
        else
        {
            ptr[0] = 0;
            ptr[1] = 0;
            ptr[2] = 0;
            ptr[3] = 0;
        }
    }
}
```

**Comment by sammycage** [comment]
Please try this example.
```cpp
#include <SFML/Graphics.hpp>
#include <memory>
#include <cmath>
#include <iostream>

#include <lunasvg/svgdocument.h>

using namespace lunasvg;

void argbTorgba(Bitmap& bitmap)
{
    std::uint8_t* ptr = bitmap.data();
    std::uint8_t* end = ptr + bitmap.height() * bitmap.width() * 4;
    while(ptr < end)
    {
        std::uint8_t a = ptr[3];
        if(a != 0)
        {
            std::uint8_t r = ptr[2];
            std::uint8_t g = ptr[1];
            std::uint8_t b = ptr[0];

            ptr[0] = (r * 255) / a;
            ptr[1] = (g * 255) / a;
            ptr[2] = (b * 255) / a;
            ptr[3] = a;
        }
        else
        {
            ptr[0] = 0;
            ptr[1] = 0;
            ptr[2] = 0;
        }

        ptr += 4;
    }
}

int main()
{
    SVGDocument document;

    clock_t start = clock();
    document.loadFromFile("tiger.svg");
    std::cout << "Parsing -- " << static_cast<double>(clock()-start) / CLOCKS_PER_SEC << "secs" << std::endl;

    double width = document.documentWidth();    
    double height = document.documentHeight();

    std::uint32_t bitmapWidth = width > 0.0 ? std::uint32_t(ceil(width)) : 512;
    std::uint32_t bitmapHeight = height > 0.0 ? std::uint32_t(ceil(height)) : 512;

    std::unique_ptr<std::uint8_t[]> pixels(new std::uint8_t[bitmapWidth*bitmapHeight*4]);
    Bitmap bitmap(pixels.get(), bitmapWidth, bitmapHeight, bitmapWidth*4);

    start = clock();
    document.render(bitmap, 96.0, 0x00000000);
    std::cout << "Rendering -- " << static_cast<double>(clock()-start) / CLOCKS_PER_SEC << "secs" << std::endl;

    argbTorgba(bitmap);

    sf::Image image;
    image.create(bitmap.width(), bitmap.height(), bitmap.data());

    sf::Texture texture;
    texture.loadFromImage(image);

    sf::Sprite sprite(texture);

    sf::RenderWindow window(sf::VideoMode(bitmap.width(), bitmap.height()), "Hello lunasvg");
    while(window.isOpen())
    {
        sf::Event event;
        while(window.pollEvent(event))
        {
            if(event.type==sf::Event::Closed)
                window.close();
        }

        window.clear(sf::Color::White);
        window.draw(sprite);
        window.display();
    }

    return 0;
}
```

**Comment by sammycage** [comment]
DOCTYPE tag is now supported. And RGBA is directly supported.

**Comment by sammycage** [comment]
> [nonsupport.zip](https://github.com/sammycage/lunasvg/files/4929036/nonsupport.zip)
> Some SVG is not supported,like this.

DOCTYPE tag is now supported.

**Comment by sammycage** [comment]
> Can you directly support RGBA!

RGBA is directly supported now.

**Comment by chengang151** [comment]
Thank you for your support, RGBA can be directly supported.DOCTYPE Tag is also supported.However, some SVG loads are problematic.The zip package is the picture in question
[reply.zip](https://github.com/sammycage/lunasvg/files/4945233/reply.zip)

**Comment by sammycage** [comment]
1.svg and 2.svg has a complicated `gradientTransform`. I remove the `gradientTransform` and it showed a better result.
 render slow - 4s.svg renders in ~1s.

**Comment by chengang151** [comment]
nothing change!

**Comment by sammycage** [comment]
> nothing change!

https://github.com/sammycage/lunasvg/commit/d86ee44651de4448b4383f6ff3dafe31549aeadd

**Comment by sammycage** [comment]
> nothing change!

Fixed : https://github.com/sammycage/lunasvg/commit/d86ee44651de4448b4383f6ff3dafe31549aeadd

**Comment by chengang151** [comment]
Can you use WeChat or alipay?

**Comment by sammycage** [comment]
Thanks for your generosity <3. But i don't have access to WeChat and alipay :( . But i do have access to aliexpress :) .

**Comment by sammycage** [comment]
render slow - 4s.svg

Faster now 82f35dca2027a86a10091d47f9a65109800fd4e2
