### ISSUE TITLE
Rotate elements

### ISSUE THREAD

**Issue by OriBibi** [sammycage/lunasvg#20]
Peace. I would love to know if it is possible for you to rotate elements? 
Something like the following link:
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform

**Comment by sammycage** [comment]
Yes.. You can use `SVGElement::setAttribute`
Example :
```cpp
SVGElement* rootElement = document.rootElement();
rootElement->setAttribute("transform", "rotate(45)");
```
