### ISSUE TITLE
Doesn't support superscripts or subscripts

### ISSUE THREAD

**Issue by mdeetjen** [sammycage/lunasvg#202]
Great work overall! The addition of images is super helpful. One other inclusion that would be helpful is superscripts and subscripts. I see that you detect `tspan`, but treat it like normal text. Here is an example of a line of such text:

`<text fill="rgb(0,0,0)" font-size="290" font-family="Roboto Mono" text-anchor="middle" transform="translate(2691.037369,328.250000) rotate(0)" >1.2 m<tspan baseline-shift = "super">3</tspan></text>`

Thank you!

**Comment by sammycage** [comment]
Thank you for your kind words! I’m glad to hear the addition of images has been helpful. Regarding your suggestion, support for `baseline-shift` has been added in the latest commit. The implementation ensures that `tspan` elements with a `baseline-shift` attribute are rendered appropriately, enabling proper positioning for superscripts, subscripts, and other baseline adjustments.

The handling of `baseline-shift` was integrated by dynamically adjusting the text rendering based on the specified value (e.g., `super`, `sub`, length or percentage). This ensures the relative alignment is visually accurate across various font sizes and families. Additionally, fallback behavior is in place for cases where the `baseline-shift` attribute is omitted or invalid.

Feel free to test it out and let me know if there are any further improvements or edge cases you'd like to see addressed! Thank you again for your valuable feedback—it’s much appreciated!
