### ISSUE TITLE
Example doesn't seem to work.

### ISSUE THREAD

**Issue by taylorh140** [sammycage/lunasvg#204]
I get a segfault when I build using meson, and try to convert render a svg.

running the svg2png program.

**Comment by sammycage** [comment]
Thanks for bringing this up! Can you share the SVG file you're using? I'd like to take a closer look.

**Comment by taylorh140** [comment]
Yeah. 
https://commons.m.wikimedia.org/wiki/File:Test.svg

I also tried using the zig build system. 
https://github.com/taylorh140/zigBuild_lunasvg

**Comment by sammycage** [comment]
Thanks for sharing the details! I’ve pushed a commit that might fix this issue on plutovg: https://github.com/sammycage/plutovg/commit/5e3c05b2f3d1af5e695e95f022f04ba7734aa0cf. Give it a try and let me know if it works for you!

**Comment by taylorh140** [comment]
It works now! Thanks.
