### ISSUE TITLE
Text width

### ISSUE THREAD

**Issue by mdeetjen** [sammycage/lunasvg#205]
Hello and thank you again for creating lunasvg and your quick responses and fixes. I have a question that may fall a bit outside the scope of the lunasvg project, and feel free to let me know if this is the case. I am using a separate package to create svg's and then I use lunasvg to render them to png's. One thing that is important to me in this process is determining the dimensions (width x height) of text elements. Right now, the way I do this is extremely clumsy: I write the text element in a new svg file, save it to disk, render it using lunasvg, and then examine the pixels to determine the text dimensions. I know that lunasvg has some internal components that compute text position - is there any way these can be exposed in the interface - or are they already exposed in some way that I am missing? Thank you!

**Comment by sammycage** [comment]
Hi! Thank you for your kind words about lunasvg. I'm glad you find it helpful.  

If I understand your question correctly, you can measure the dimensions of text elements without rendering them by using the `Element::getGlobalBoundingBox()` method. This allows you to compute the position and size (width and height) of text elements directly from the SVG without needing to render them to an image.  

Here’s an example workflow you can follow:

`hello-text.svg`

```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="300" height="200">
  <text id="text1" x="10" y="30" font-family="Arial" font-size="20" fill="black">
    Text Element 1
  </text>

  <text id="text2" x="50" y="80" font-family="Verdana" font-size="16" fill="blue">
    Text Element 2
  </text>

  <text id="text3" x="100" y="150" font-family="Times New Roman" font-size="24" fill="green">
    Text Element 3
  </text>
</svg>
```

```cpp
auto document = Document::loadFromFile("hello-text.svg");
auto element1 = document->getElementById("text1");
auto element2 = document->getElementById("text2");
auto element3 = document->getElementById("text3");

// Retrieve the global bounding box (position and size) of each element
auto bbox1 = element1.getGlobalBoundingBox();
auto bbox2 = element2.getGlobalBoundingBox();
auto bbox3 = element3.getGlobalBoundingBox();

// Display the position and size (x, y, width, height) of each element
std::cout << "Text 1 is located at ("
          << bbox1.x << ", " << bbox1.y
          << ") with a size of (" << bbox1.w
          << " x " << bbox1.h << ")" << std::endl;
std::cout << "Text 2 is located at ("
          << bbox2.x << ", " << bbox2.y
          << ") with a size of (" << bbox2.w
          << " x " << bbox2.h << ")" << std::endl;
std::cout << "Text 3 is located at ("
          << bbox3.x << ", " << bbox3.y
          << ") with a size of (" << bbox3.w
          << " x " << bbox3.h << ")" << std::endl;
```

**Comment by sammycage** [comment]
https://github.com/sammycage/lunasvg/issues/165#issuecomment-2334613849

**Comment by mdeetjen** [comment]
Works great thank you!
