### ISSUE TITLE
How to add this library as external using git submodule?

### ISSUE THREAD

**Issue by lwyj123** [sammycage/lunasvg#23]
I cannot find variables like `LUNASVG_INCLUDE_DIRS` and `LUNASVG_LIBRARIES`  to use.

```
add_subdirectory(${EXTERNAL_DIR}/lunasvg)
target_include_directories(main PRIVATE ${LUNASVG_INCLUDE_DIRS})
target_link_libraries(main ${LUNASVG_LIBRARIES})
```

**Comment by sammycage** [comment]
```
add_subdirectory(${EXTERNAL_DIR}/lunasvg)
target_link_libraries(main lunasvg)
```

**Comment by lwyj123** [comment]
> ```
> add_subdirectory(${EXTERNAL_DIR}/lunasvg)
> target_link_libraries(main lunasvg)
> ```
> 
> Lemme known if it works 😃

Thanks for your answer.

If I use this way, I need to build and install the package firstly.
```
cd lunasvg
mkdir build
cd build
make -j 2
make install
```

But the other package I used before, I don't need to do that things manually. is the command mentioned above necessary?

**Comment by sammycage** [comment]
No.. You don't need to build lunasvg separating anymore. The main CMakeList.txt will build it for you.

**Comment by lwyj123** [comment]
OK, I used this method before but it does't work, I will check this method later again.

**Comment by lwyj123** [comment]
@sammycage I just got this error

![image](https://user-images.githubusercontent.com/9214496/105623803-9cc11f80-5e57-11eb-8e43-073d917ec632.png)

And I need to run `make install` myself

![image](https://user-images.githubusercontent.com/9214496/105623828-d85be980-5e57-11eb-8cce-21ff50de95f3.png)

**Comment by sammycage** [comment]
`#include <svgdocument.h>` not `#include <lunasvg/svgdocument.h>`

**Comment by lwyj123** [comment]
@sammycage not works.
![image](https://user-images.githubusercontent.com/9214496/105656331-e9126b00-5efc-11eb-87c2-1bf7b1381f9b.png)

And I get the include code from https://github.com/sammycage/lunasvg/issues/18, will the usage be different?

**Comment by lwyj123** [comment]
Oh, I just updated the submodule, It works. Seems the update https://github.com/sammycage/lunasvg/commit/35cf0a2c986d6dba789e364bff099d394c096e6d change the behavior.

**Comment by lwyj123** [comment]
Could you update the documents for later users if you have the time?
