### ISSUE TITLE
Text anchor is not working properly

### ISSUE THREAD

**Issue by JackGit3** [sammycage/lunasvg#25]
I'm trying to draw text based off this svg string: 

```
<svg xmlns="http://www.w3.org/2000/svg" version="1.2" baseProfile="tiny" width="341.33333333333326" height="176" viewBox="-33.33333333333333 1 341.3333333333333 176"></path></g><text x="5" y="160" te
xt-anchor="end" font-size="40" font-family="Arial" stroke-width="4" stroke="none" fill="black" >A</text><text x="195" y="160" text-anchor="start" font-size="40" font-family="Arial" stroke-width="4" stroke="none" fill="black" >1-327</text></svg>
```

I tested it online and it works, I'm guessing however some setting inside this svg isn't supported yet? My question is what can I remove or change about this svg while keeping the basic text and text location and have it show up using lunasvg?

Tested using built 1.4.2 version of the library, or should I be just using master?

Any help is appreciated, thank you.

**Comment by sammycage** [comment]
Text rendering requires font so you have to load font before rendering.

You can load font using `SVGDocument::loadFontFromFile`.
Please take a look at this issue #21

**Comment by JackGit3** [comment]
Ok thanks I text works now, however now I have an issue with the outline fill for the text being offset. For the following svg:
`<svg xmlns="http://www.w3.org/2000/svg" version="1.2" baseProfile="tiny" width="341.33333333333326" height="176" viewBox="-33.33333333333333 1 341.3333333333333 176"><text x="5" y="160" text-anchor="end" font-size="40" font-family="Arial" stroke-width="10" stroke-linecap="round" stroke-linejoin="round" stroke="rgb(239, 239, 239)" fill="none" >A</text><text x="195" y="160" text-anchor="start" font-size="40" font-family="Arial" stroke-width="10" stroke-linecap="round" stroke-linejoin="round" stroke="rgb(239, 239, 239)" fill="none" >1-327</text><g transform="translate(0,0)" stroke-width="4" stroke="black" fill="none" ><path d="M100,40L100,15" stroke-width="14" stroke-linecap="round" stroke-linejoin="round" stroke="rgb(239, 239, 239)" fill="none" ></path></g><path d="M25,50 l150,0 0,100 -150,0 z Z" stroke-width="14" stroke-linecap="round" stroke-linejoin="round" stroke="rgb(239, 239, 239)" fill="none" ></path><path d="M25,50 l150,0 0,100 -150,0 z" stroke-width="4" stroke="black" fill="rgb(128,224,255)" fill-opacity="1" ></path><path d="M25,50 L175,150 M25,150 L175,50" stroke-width="4" stroke="black" fill="black" ></path><path d="M75,140 C75,125 100,125 100,140 C100,125 125,125 125,140" stroke-width="4" stroke="black" fill="none" ></path><g transform="translate(0,0)" stroke-width="4" stroke="black" fill="none" ><path d="M100,40L100,15" ></path></g><text x="5" y="160" text-anchor="end" font-size="40" font-family="Arial" stroke-width="4" stroke="none" fill="black" >A</text><text x="195" y="160" text-anchor="start" font-size="40" font-family="Arial" stroke-width="4" stroke="none" fill="black" >1-327</text></svg>`

Everything displays correctly except the letter A on the left side, the white outline does not match up to where the letter is so that half of the letter is outside of the white outline, but everything else looks correct. For reference this is what it should look like:

<svg xmlns="http://www.w3.org/2000/svg" version="1.2" baseProfile="tiny" width="341.33333333333326" height="176" viewBox="-33.33333333333333 1 341.3333333333333 176"><text x="5" y="160" text-anchor="end" font-size="40" font-family="Arial" stroke-width="10" stroke-linecap="round" stroke-linejoin="round" stroke="rgb(239, 239, 239)" fill="none" >A</text><text x="195" y="160" text-anchor="start" font-size="40" font-family="Arial" stroke-width="10" stroke-linecap="round" stroke-linejoin="round" stroke="rgb(239, 239, 239)" fill="none" >1-327</text><g transform="translate(0,0)" stroke-width="4" stroke="black" fill="none" ><path d="M100,40L100,15" stroke-width="14" stroke-linecap="round" stroke-linejoin="round" stroke="rgb(239, 239, 239)" fill="none" ></path></g><path d="M25,50 l150,0 0,100 -150,0 z Z" stroke-width="14" stroke-linecap="round" stroke-linejoin="round" stroke="rgb(239, 239, 239)" fill="none" ></path><path d="M25,50 l150,0 0,100 -150,0 z" stroke-width="4" stroke="black" fill="rgb(128,224,255)" fill-opacity="1" ></path><path d="M25,50 L175,150 M25,150 L175,50" stroke-width="4" stroke="black" fill="black" ></path><path d="M75,140 C75,125 100,125 100,140 C100,125 125,125 125,140" stroke-width="4" stroke="black" fill="none" ></path><g transform="translate(0,0)" stroke-width="4" stroke="black" fill="none" ><path d="M100,40L100,15" ></path></g><text x="5" y="160" text-anchor="end" font-size="40" font-family="Arial" stroke-width="4" stroke="none" fill="black" >A</text><text x="195" y="160" text-anchor="start" font-size="40" font-family="Arial" stroke-width="4" stroke="none" fill="black" >1-327</text></svg>

**Comment by sammycage** [comment]
Please can you try https://github.com/sammycage/lunasvg/releases/tag/v1.3.1

Let me know whether the problem is from PlutoVG.

**Comment by JackGit3** [comment]
Ok I'll try that tonight, will let you know in a few hours, thanks!

**Comment by sammycage** [comment]
> Ok I'll try that tonight, will let you know in a few hours, thanks!

Don't worry about it... PlutoVG is prefect

The problem is matrix translation

**Comment by sammycage** [comment]
Thank you for reporting this issue

**Comment by JackGit3** [comment]
Awesome thanks, however I still seem to be having the same issue even though I pulled the latest master branch, built it and copied over the new .lib file and header files. Could it just be something on my end then?
