### ISSUE TITLE
Feature request: text path

### ISSUE THREAD

**Issue by akujiki-shin** [sammycage/lunasvg#26]
Hi,

First thank you for lunasvg, I love how fast it is compared to others.

TextPath aren't supported yet and I don't see it mentioned in the todo,
so today it is not possible to do something like:

![TextPath](https://user-images.githubusercontent.com/79542622/108903997-3f6aea80-761e-11eb-83f2-c416cb767c1b.jpg)

This example also makes use of the attributes "textLength", "textAdjust" and "startOffset".

(svg: [TextPath.zip](https://github.com/sammycage/lunasvg/files/6031678/TextPath.zip))

Would it be possible to add it to the list ?

**Comment by sammycage** [comment]
The current text support is sub mininal. I will focus more on text handling ie TSpan, TRef and TextPath. 

> Would it be possible to add it to the list?

I will update todo list later

**Comment by aku-o** [comment]
Perfect, Thank you for the quick answer.

**Comment by sammycage** [comment]
Hi,

Thank you for your kind words about Lunasvg! TextPath won't be worked on for now. However, the good news is that tspan and text elements are now fully supported.
