### ISSUE TITLE
The stroke-dasharray attribute of path is not supported?

### ISSUE THREAD

**Issue by goujia-hnu** [sammycage/lunasvg#27]
**How to render a path with stroke-dasharray attribute?**
**<svg width="212" height="83" viewBox="0 0 212 83" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M15 9H207C209.209 9 211 10.7909 211 13V34C211 36.2091 209.209 38 207 38H15" stroke="#CCCCCC" stroke-linecap="round" stroke-dasharray="4 4"/>
<path d="M15 48H207C209.209 48 211 49.7909 211 52V73C211 75.2091 209.209 77 207 77H15" stroke="#CCCCCC" stroke-linecap="round" stroke-dasharray="4 4"/>
</svg>**

**Comment by sammycage** [comment]
`stroke-dasharray` is supported.

An SVG file or data will be useful for further investigations

**Comment by goujia-hnu** [comment]
[progress_bar_bk.zip](https://github.com/sammycage/lunasvg/files/6077600/progress_bar_bk.zip)

**Comment by sammycage** [comment]
Please can you try https://github.com/sammycage/lunasvg/releases/tag/v1.3.1

Let me know whether the problem is from PlutoVG.

**Comment by sammycage** [comment]
![progress_bar_bk svg](https://user-images.githubusercontent.com/29164324/109862053-474f0e00-7c60-11eb-8ee6-edd9a14761d5.png)

Everything is perfect

**Comment by goujia-hnu** [comment]
My version is not the latest, I will update the next version and try again. thanks landlord.
