### ISSUE TITLE
Generating SVG

### ISSUE THREAD

**Issue by boxerab** [sammycage/lunasvg#28]
Nice project!
I am looking for a simple library to generate simple svg files: only multiple pieces of text 
and multiple bounding boxes. Would it be easy to carve out the svg generating code into a separate
part of the library? I can work on it, just wondering if it is easy to do ?
Thanks!
Aaron

**Comment by sammycage** [comment]
> I am looking for a simple library to generate simple svg files: only multiple pieces of text
and multiple bounding boxes. 

Please can you give me an example

> Would it be easy to carve out the svg generating code into a separate
part of the library?

If lunasvg can do the job, detaching the library isn't that difficult.

**Comment by boxerab** [comment]
@sammycage thanks. I don't need any rendering, just creation and manipulation of SVG images, as XML. For my purposes, I will just use a simple header only library for this.
