### ISSUE TITLE
Consistency in Scaling

### ISSUE THREAD

**Issue by Reputeless** [sammycage/lunasvg#3]
Hi, @sammycage.

When I changed `documentWidth` and `documentHeight` in the svg2png example as follows, the image content was cropped in some cases.
```C++
        double documentWidth = document.documentWidth() * 0.5;
        double documentHeight = document.documentHeight() * 0.5;
```

#### scaled:
![image](https://user-images.githubusercontent.com/3108136/88460896-923ec100-ceda-11ea-9485-69cdfab2dd8b.png)

#### cropped:
![image](https://user-images.githubusercontent.com/3108136/88460852-50157f80-ceda-11ea-987f-4475d3e2d007.png)

Is there a consistent way to scale the content to fit the `lunasvg::Bitmap` size without cropping?

**svgren** has a option to request a size, and it works as I expect.
https://github.com/igagis/svgren/blob/ca45437ab6b89430c8336404889b00bc5f0147ef/src/svgren/render.hpp#L12-L27

[Here](https://github.com/igagis/svgren/tree/master/tests/samples/testdata) are the test files.

**Comment by sammycage** [comment]
"scale to fit in the viewPort" will be added on next commit.

**Comment by sammycage** [comment]
Added : https://github.com/sammycage/lunasvg/commit/7c0ddbf547285d06935571f883e505ac3ac28982

**Comment by sammycage** [comment]
Added but not tested : https://github.com/sammycage/lunasvg/commit/7c0ddbf547285d06935571f883e505ac3ac28982.

**Comment by Reputeless** [comment]
I tried the latest code d60fbc7 with the following modification:

```C++
double documentWidth = document.documentWidth() * 0.5;
double documentHeight = document.documentHeight() * 0.5;
```
It works fine for [car.svg](https://github.com/igagis/svgren/blob/master/tests/samples/testdata/car.svg), but now the content of the [3.072.svg](https://github.com/igagis/svgren/blob/master/tests/samples/testdata/3.072.svg) is scaled down incorrectly.

#### car.svg
![svg_1](https://user-images.githubusercontent.com/3108136/88504913-fc598200-d010-11ea-82b4-3664dc2ea11a.png)

#### 3.072.svg
![svg_2](https://user-images.githubusercontent.com/3108136/88504929-04b1bd00-d011-11ea-8a56-a7ed0e38c902.png)

**Comment by sammycage** [comment]
is it same with svgren?

**Comment by sammycage** [comment]
The problem is that `viewBox` is not specified in these file. But i am currently working on a way to specify the `viewBox` without modifying the content of the file. Like this.
```cpp
...

SVGView view(document.getBbox());

document.render(bitmap, view, dpi, bgColor);
...

```

**Comment by sammycage** [comment]
Added : https://github.com/sammycage/lunasvg/commit/7ded6068ad442d2491455ed91ebce87733c973e1

**Comment by sammycage** [comment]
Added : https://github.com/sammycage/lunasvg/commit/aed8047ef9aed0cae09e774706b539a43f472c64

**Comment by Reputeless** [comment]
Now it works fine! Thank you.

![image](https://user-images.githubusercontent.com/3108136/88679614-8ea17900-d12a-11ea-88b1-b7e1bde11e25.png)

![image](https://user-images.githubusercontent.com/3108136/88679567-847f7a80-d12a-11ea-9df8-a5912b4a9629.png)

**Comment by sammycage** [comment]
Added renderToBitmap  : https://github.com/sammycage/lunasvg/commit/fc6eaff2785a550aaed34550a095accbf00829bf
```cpp
...
SVGDocument document;
document.loadFromFile("filename.svg");
Bitmap bitmap = document.renderToBitmap();
...
```
