### ISSUE TITLE
Updating text element content

### ISSUE THREAD

**Issue by mxdamien** [sammycage/lunasvg#31]
Hi !

We are using SVGs as a template for engineering drawings. We want to dynamically replace the content of specific text elements to display calculated values. We tried to use _SVGElement::insertContent(...)_ for this but we were not succesful.

`SVGElement* test = document.getElementById("text1");
test->insertContent("12345", InsertPosition::AfterBegin);`

We traced it down into the parser and found out that the TagType is detected as _KTagPCData_ but since the blocks stack is empty the if-branch for this Tagtype is not executed.

https://github.com/sammycage/lunasvg/blob/2d6d80e835a607a3e4e148620b9f376f479a2d31/source/svgparser.cpp#L109-L116

We were able to reach our desired functionality with changes to the parser but we are not sure if we are possibly just using the existing possibilities in a wrong way.

Update:

I pushed the changes we are testing at the moment to our fork

https://github.com/mxdamien/lunasvg/commit/36b824eee63f65b753e72830e9dfa6d27fb070d4

Regards,

David

**Comment by mxdamien** [comment]
Hi again,

We did not encounter any drawbacks to the changes we have made so far. I created a pulled request for the changes.

Regards,

David

**Comment by sammycage** [comment]
Since the API has changed, I will close this issue and the pull request. Thank you <3
