### ISSUE TITLE
SVG containing StyleSheet is not rendered correctly

### ISSUE THREAD

**Issue by tonyvsuk** [sammycage/lunasvg#34]
Is the likely cause of this that they are just not supported?

Thanks in advance,
 
Tony.

**Comment by sammycage** [comment]
Please can you send me the icon?

**Comment by tonyvsuk** [comment]
Here it is. I've had to change the file extension to txt as github do not allow svg files.

[Action_16x.svg.txt](https://github.com/sammycage/lunasvg/files/6289810/Action_16x.svg.txt)

**Comment by tonyvsuk** [comment]
Here is a 2nd example.
[AbsolutePosition_16x.png.txt](https://github.com/sammycage/lunasvg/files/6289814/AbsolutePosition_16x.png.txt)

**Comment by sammycage** [comment]
StyleSheet is not yet supported..

**Comment by tonyvsuk** [comment]
Thanks, I assumed it was something like this. Shame, the Visual Studio Icon library is full of useful images that can be used royalty free.

**Comment by igagis** [comment]
@tonyvsuk  you can try https://github.com/cppfw/svgren

**Comment by tonyvsuk** [comment]
Thanks for the suggestion, I tried but found it too difficult to work out how to use it (or even get it installed).

**Comment by sammycage** [comment]
> Thanks, I assumed it was something like this. Shame, the Visual Studio Icon library is full of useful images that can be used royalty free.

At Smoke Testing Stage. @tonyvsuk you can help any other troubleshooting file

**Comment by tonyvsuk** [comment]
I got them from the MS Visual Studio 2019 icon library, you can get it at
https://www.microsoft.com/en-gb/download/details.aspx?id=35825

Hope this helps. I'm using a different library at the moment, but will switch to this once I've got a deadline out of the way.

**Comment by sammycage** [comment]
> Here it is. I've had to change the file extension to txt as github do not allow svg files.
> 
> [Action_16x.svg.txt](https://github.com/sammycage/lunasvg/files/6289810/Action_16x.svg.txt)

@tonyvsuk StyleSheet is now supported

![Action_16x svg txt](https://user-images.githubusercontent.com/29164324/125203910-9d693900-e272-11eb-967e-e51bd16e16ea.png)
