### ISSUE TITLE
Library is forcefully built as static

### ISSUE THREAD

**Issue by LHLaurini** [sammycage/lunasvg#38]
https://github.com/sammycage/lunasvg/blob/5f4d0388c1259a6acc884cab90fc655ec5fd95a1/CMakeLists.txt#L10

Is there any reason for forcing the library to always be statically linked? Wouldn't it be a better idea to just use [`BUILD_SHARED_LIBS`](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html) and allow the developer to choose?

**Comment by sammycage** [comment]
> Is there any reason for forcing the library to always be statically linked?

I explicitly set the library target as STATIC, because public headers do not export any symbols on Windows.

> Wouldn't it be a better idea to just use BUILD_SHARED_LIBS and allow the developer to choose?

It will be a good idea. When I have time, I'll work on it. Pull request will be highly appreciated.

**Comment by LHLaurini** [comment]
I'll give it a shot. Shouldn't take long.
