### ISSUE TITLE
Godot Engine module

### ISSUE THREAD

**Issue by fire** [sammycage/lunasvg#47]
Hi,

I'm trying out your SVG code in Godot Engine.

https://github.com/godot-extended-libraries/lunasvg

Cheers.

**Comment by fire** [comment]
Here's a photo.

The editor icons and the camera are using lunasvg.

![image](https://user-images.githubusercontent.com/32321/121793544-f9c63380-cbb4-11eb-9e07-98da60ab3339.png)

**Comment by sammycage** [comment]
Wow

**Comment by fire** [comment]
I have made a branch for Godot Engine because someone wasn't able to do the necessary changes to test it.

https://github.com/fire/godot/tree/lunasvg

There's a way to get Windows, Linux and MacOS binaries from Github workflow artifacts.
