### ISSUE TITLE
Add the ability to write SVG

### ISSUE THREAD

**Issue by fire** [sammycage/lunasvg#48]
Create shapes and output svg.

* points
* lines
* fills
* shapes
* etc.

**Comment by sammycage** [comment]
Buddy.. You can use library like [libboard](https://github.com/c-koi/libboard) or [pugixml](https://github.com/zeux/pugixml) to create svg. You can send it to lunasvg for rendering.

**Comment by Calinou** [comment]
I agree writing SVG is better left to XML writer libraries. Let's keep this library focused on reading SVGs well 🙂

**Comment by fire** [comment]
@Calinou I was trying to recreate your light to dark theme and it seemed like you were modifying the svg before it is read.

https://github.com/zeux/pugixml looks like the most compatible approach because it's license compatible. 

`libboard` isn't.
