### ISSUE TITLE
Differences from the reference image

### ISSUE THREAD

**Issue by Reputeless** [sammycage/lunasvg#5]
SVG: https://github.com/igagis/svgren/blob/master/tests/samples/testdata/3.072.svg

#### reference: https://github.com/igagis/svgren/blob/master/tests/samples/testdata/3.072.png
![3 072](https://user-images.githubusercontent.com/3108136/89506681-73a7c680-d806-11ea-9589-eb28af791e40.png)

#### Google Chrome 84
![image](https://user-images.githubusercontent.com/3108136/89510533-a4d6c580-d80b-11ea-80db-1dd55a451aa3.png)

#### lunasvg e7ffce4 (agg) 
![image](https://user-images.githubusercontent.com/3108136/89510308-5d503980-d80b-11ea-979e-667ec4f88b30.png)

**Comment by sammycage** [comment]
SVG Filter Primitives is not implemented.

**Comment by Reputeless** [comment]
Thanks, I understand.
But this seems some sort of bug.
![image](https://user-images.githubusercontent.com/3108136/89592801-8662df80-d888-11ea-8dde-44ef29227e87.png)

Such an artifact appears in https://github.com/igagis/svgren/blob/master/tests/samples/testdata/0.451.svg too.
![image](https://user-images.githubusercontent.com/3108136/89593325-d3938100-d889-11ea-9eed-a946ca3148b7.png)

**Comment by sammycage** [comment]
Fixed : https://github.com/sammycage/lunasvg/commit/e9022213c3d84d12f4990be35b7cff69eea8162c

Thanks for your support.

**Comment by sammycage** [comment]
Fixed : https://github.com/sammycage/lunasvg/commit/e9022213c3d84d12f4990be35b7cff69eea8162c

Thanks for your support.

**Comment by sammycage** [comment]
Fixed : https://github.com/sammycage/lunasvg/commit/e9022213c3d84d12f4990be35b7cff69eea8162c

Thank you for reporting this issue.
