### ISSUE TITLE
Add a supported SVG element matrix

### ISSUE THREAD

**Issue by fire** [sammycage/lunasvg#51]
| **SVG Element** | **Supported** |
|:--|:-:|
| svg | 👍 |
| g | 👍 |
| clipPath | 👍 |
| defs | 👍 |
| ellipse | 👍 |
| line | 👍 |
| path | 👍 |
| polyline | 👍 |   
| polygon | 👍 |
| rect | 👍 |
| marker | 👍 |
| mask | 👍 |
| linearGradient | 👍 |
| radialGradient | 👍 |
| pattern | 👍 |
| solidColor | 👍 |
| stop | 👍 |
| symbol | 👍 |
| text | 👍 |
| use | 👍 |
| text | ⛔️ |
| filter | ⛔️ |
| image| ⛔️ |
| style | ⛔️ |

**Comment by sammycage** [comment]
OK

**Comment by fire** [comment]
https://github.com/sammycage/lunasvg/pull/52
