### ISSUE TITLE
Sliding over SVG?

### ISSUE THREAD

**Issue by erentknn** [sammycage/lunasvg#54]
Currently I am using nanosvg on some project and I want to change it with lunasvg because of performance issues. However when I try to render some SVG string I get whole SVG rendered like this (btw I am using translate method to shift the svg.): 
![luna_out](https://user-images.githubusercontent.com/48161058/124117954-6bd5be00-da79-11eb-98c8-fc36c17f9bca.png)

However I want to process this normally big (7k x 7k) image tile by tile. With nanosvg I could do this with no overhead. 
Is there any way to achieve this in lunasvg?
Currently my code is like this:
```
	svgImage = lunasvg::Document::loadFromData(svgStr);
	svgImage->translate(-x, -y) ;
	lunasvg::Bitmap bitmap = svgImage->renderToBitmap(width, height);
        
        // opencv section
        auto res = cv::Mat(height, width, CV_8UC4);
	res.data = bitmap.data();
	cv::cvtColor(res, res, CV_RGBA2GRAY);
	res = res > 0;
```

**Comment by sammycage** [comment]
Please can you give me the SVG file

**Comment by erentknn** [comment]
sure, [svg.zip](https://github.com/sammycage/lunasvg/files/6748810/svg.zip)

**Comment by sammycage** [comment]
> sure, [svg.zip](https://github.com/sammycage/lunasvg/files/6748810/svg.zip)

I can see only white square

**Comment by erentknn** [comment]
oops, sorry. fixed it now: [svg.zip](https://github.com/sammycage/lunasvg/files/6749425/svg.zip)

**Comment by sammycage** [comment]
Please can you give me the nanosvg example code so that I can fully understand what you are trying to do.

**Comment by erentknn** [comment]
Here it is, for explanation shiftingValue is the original coordinates in the big image (think like I have 40k x 40k image and this is a small piece in it) and I am shifting to that coordinates so I can render the right place. It's the same as in svgImage->translate(). But I provided this in the svg file for you so probably those are, shifting coordinates, unnecessary now. I hope that has been explanatory.

```
	const auto svgStrPtr = new char[svgStr.length() + 1];
	svgStrPtr[svgStr.length()] = '\0';
	strcpy(svgStrPtr, svgStr.c_str());
	nsvgImage = nsvgParse(svgStrPtr, "px", 96.0f);

	auto rast = nsvgCreateRasterizer(); // Create rasterizer
	auto img = static_cast<unsigned char*>(malloc(widthCalc * heightCalc * 4)); 
	nsvgRasterize(rast, nsvgImage, -(x - shiftingValue), -(y - shiftingValue), 1, img, widthCalc, heightCalc, widthCalc * 4); 
	auto res = cv::Mat(heightCalc, widthCalc, CV_8UC4);
	res.data = img;
	cv::cvtColor(res, res, CV_RGBA2GRAY);
	res = res > 0;
	nsvgDeleteRasterizer(rast); 
	free(img);
```

**Comment by sammycage** [comment]
Thanks. I will work on it this weekend.

**Comment by sammycage** [comment]
@erentknn if you are still having issues. Please let me know

**Comment by erentknn** [comment]
Hey @sammycage, thank you for quick response. but unfortunately it's still not working. I am using the same code as above.

**Comment by sammycage** [comment]
Sample code

```cpp
auto document = Document::loadFromData("a.svg");
document->translate(-50, -50);
```

Before :

![a svg](https://user-images.githubusercontent.com/29164324/124388335-5f9c6b80-dcda-11eb-9554-f1007fb19341.png)

After :

![after svg](https://user-images.githubusercontent.com/29164324/124388403-c0c43f00-dcda-11eb-8586-3e8ff032b8d4.png)

**Comment by sammycage** [comment]
> But I provided this in the svg file for you so probably those are, shifting coordinates, unnecessary now.

Please make sure that you are not using the modified file

**Comment by erentknn** [comment]
I think I explained the problem wrong. Translating works OK. What I am trying to do is sliding over the SVG Image, with nanosvg in my first output is like this: 
![aa](https://user-images.githubusercontent.com/48161058/124388638-6cc25600-dcec-11eb-8b22-f1767eee5326.png)

and second is this:
![ab2](https://user-images.githubusercontent.com/48161058/124388648-7350cd80-dcec-11eb-85ee-2dc371b818b2.png)

Second image is the tagged area (approximately):
![axf](https://user-images.githubusercontent.com/48161058/124388744-db9faf00-dcec-11eb-83e9-de5064699660.png)

Like this, I want to loop on the whole SVG tile by tile. 
BTW after your modification I can't get any output. Just blank image.

**Comment by sammycage** [comment]
@erentknn Did you mean Scaling?

**Comment by sammycage** [comment]
@erentknn is the height and width in `lunasvg::Bitmap bitmap = svgImage->renderToBitmap(width, height)` different from the one in the file.

**Comment by sammycage** [comment]
> However I want to process this normally big (7k x 7k) image tile by tile.

Now I understand what you are trying to do

Use `Document::render` instead

**Comment by erentknn** [comment]
> @erentknn is the height and width in `lunasvg::Bitmap bitmap = svgImage->renderToBitmap(width, height)` different from the one in the file.

Yes, width and height are 1024. 


> Now I understand what you are trying to do
> 
> Use `Document::render` instead
> 
> Example :
> 
> ```c++
> Bitmap bitmap{width, height};
> document->translate(-x, -y);
> document->render(bitmap);
> ```

Now I can render the first tile correctly. But after that it's blank image again.

**Comment by sammycage** [comment]
@erentknn With the latest commit you can now do this

```cpp
Bitmap bitmap{width, height};
Matrix matrix{1, 0, 0, 1, -x, -y};
document->render(bitmap, matrix);
```

**Comment by erentknn** [comment]
THANK YOU, It worked as expected.
