### ISSUE TITLE
Cannot parse some SVG's tile by tile

### ISSUE THREAD

**Issue by erentknn** [sammycage/lunasvg#55]
I have two SVG's. One is smaller (12k x 7k) other one is bigger (28k x 32k) I can parse the smaller one tile by tile with no problem. But with other one I get Access Violation error. I triple checked the code and cannot find any problem. Here is a sample code to reproduce it:

	std::vector<std::vector<float>> tileParamList; // coordinates from the json file
	const int width = 1024;
	const int height = 1024;
	auto svgImage = lunasvg::Document::loadFromData(svgStr);

	for (int i = 0; i < tileParamList.size(); i++)
	{
		lunasvg::Bitmap bitmap{ width, height };
		lunasvg::Matrix matrix{ 1, 0, 0, 1, -tileParamList[i][0], -tileParamList[i][1] };
		
		svgImage->render(bitmap, matrix); <----------- HERE

		auto res = cv::Mat(height, width, CV_8UC4);
		res.data = bitmap.data();
		cv::cvtColor(res, res, CV_RGBA2GRAY);
		res = res > 0;
	}

SVG and tileList can be found here: [broken.zip](https://github.com/sammycage/lunasvg/files/6776769/broken.zip)
And other SVG can be found here (One that works correctly. Note: First few iterations might be blank image.): [notbroken.zip](https://github.com/sammycage/lunasvg/files/6776783/notbroken.zip)

**Comment by sammycage** [comment]
Short overflow in plutovg😢😢😢

**Comment by sammycage** [comment]
@erentknn Did you have access to cairo library?

**Comment by erentknn** [comment]
@sammycage No, I never used it before.

**Comment by sammycage** [comment]
@erentknn Are you using Linux or Windows?

**Comment by erentknn** [comment]
@sammycage Windows.

**Comment by sammycage** [comment]
OK..  I will try to replace plutovg with [Blend2D](https://github.com/blend2d/blend2d). It is very fast compare to other renderers.
You will be using it until i fix this issue.

**Comment by erentknn** [comment]
> Short overflow in plutovg 🤯🤯🤯

BTW, isn't it easier to fix the short overflow rather than replacing the all library?

**Comment by sammycage** [comment]
The problem is from freetype code inside PlutoVG... This makes it more difficult for me to fix it.

**Comment by sammycage** [comment]
Let me explain the problem to you.

(FT_Outline)[https://www.freetype.org/freetype2/docs/reference/ft2-outline_processing.html] can only handle maximum of 32,767 points. But the svg file you provided has only just one path element which has 175,537 points.

**Comment by erentknn** [comment]
Wow. That's a lot of points. Thank you for the explanation. Is there anything I can do for help?

**Comment by sammycage** [comment]
Is the SVG file manually generated?

> Is there anything I can do for help?

Try decrease the number of points by increasing the number of path elements with less points.

**Comment by erentknn** [comment]
Yes, I am creating SVG from the contours found earlier. 

> Try decrease the number of points by increasing the number of path elements with less points.

I will try this.

**Comment by sammycage** [comment]
8

**Comment by sammycage** [comment]
> Yes, I am creating SVG from the contours found earlier.

If you need my help, please let me know.

**Comment by erentknn** [comment]
I split the path into multiple paths but result was not the same as before on both SVG's. Probably because of contours that are on multiple tiles breaks something.

**Comment by sammycage** [comment]
very fast 
[lunasvg-blend2d.zip](https://github.com/sammycage/lunasvg/files/6794862/lunasvg-blend2d.zip)
