### ISSUE TITLE
Use lunasvg in iOS Xcode project

### ISSUE THREAD

**Issue by FlashTang** [sammycage/lunasvg#57]
Is it possible to use lunasvg in iOS? 
so far so good 
```
char *input_image = strdup([[[NSBundle mainBundle] pathForResource:@"1" ofType:@"svg"] UTF8String]);

    NSLog(@"%s",input_image);
    auto document = Document::loadFromFile(input_image);
 
    auto bitmap = document->renderToBitmap();

    NSLog(@"%d",bitmap.width()); 
```

Seems it works , but how can I convert  lunasvg::Bitmap to UIImage (iOS)
I try use stb_image_write.h to write the file to the iOS Documents folder ,then load it as UIImage
but got an error 
`Undefined symbol: _stbi_write_png`

So I make the liblunasvg.a , and included in the xcode project

But another error 
`/Users/tang/Desktop/lunasvg_/lunasvg.xcodeproj Building for iOS, but the linked library 'liblunasvg.a' was built for macOS.`

Any solution?
Thanks

**Comment by sammycage** [comment]
Firstly I don't know how iOS Xcode works.

> I try use stb_image_write.h to write the file to the iOS Documents folder ,then load it as UIImage.

This is a terrible solution

> but got an error ```Undefined symbol: _stbi_write_png```

`_stbi_write_png` is not part of `stb_image_write.h`

> Any solution?

Please show me your build steps
