### ISSUE TITLE
Issues linking, compiler statement fine

### ISSUE THREAD

**Issue by Jamesthe1** [sammycage/lunasvg#58]
I built the library from source via `cmake ..` inside my build folder, then used the generated Visual Studio project to build all files. In Debug, I copied the newly-generated library file into my MinGW's library path. After, I created the following example project:
```c++
#include <lunasvg.h>

int main () {
	using namespace lunasvg;

	auto doc = Document::loadFromFile ("svgtest.svg");
	if (doc == nullptr)
		return 1;

	doc->rotate (45);
	Bitmap bitmap = doc->renderToBitmap ();

	return 0;
}
```
then compiled with `g++ test.cpp -o b.exe -llunasvg`:
```
C:\Users\james\AppData\Local\Temp\ccr7qqTq.o:test.cpp:(.text+0xc0): undefined reference to `lunasvg::Document::loadFromFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>
> const&)'
C:\Users\james\AppData\Local\Temp\ccr7qqTq.o:test.cpp:(.text+0x10c): undefined reference to `lunasvg::Document::rotate(double)'
C:\Users\james\AppData\Local\Temp\ccr7qqTq.o:test.cpp:(.text+0x140): undefined reference to `lunasvg::Document::renderToBitmap(unsigned int, unsigned int, unsigned int) const'
C:\Users\james\AppData\Local\Temp\ccr7qqTq.o:test.cpp:(.text$_ZNKSt14default_deleteIN7lunasvg8DocumentEEclEPS1_[__ZNKSt14default_deleteIN7lunasvg8DocumentEEclEPS1_]+0x14): undefined reference to `lunasv
g::Document::~Document()'
collect2.exe: error: ld returned 1 exit status
```
No errors had shown up in my IDE, and had the library not existed, MinGW would have told me. Have I missed a step?

**Comment by sammycage** [comment]
Please try `cmake .. BUILD_SHARED_LIBS=NO`

**Comment by sammycage** [comment]
Please try this `cmake .. -DBUILD_SHARED_LIBS=ON`

**Comment by Jamesthe1** [comment]
Compilation process was successful again, but this time, using the same options, it gave me this error:
```
C:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/lib/../lib/lunasvg.dll: file not recognized: File format not
 recognized
collect2.exe: error: ld returned 1 exit status
```

**Comment by sammycage** [comment]
> I built the library from source via cmake .. inside my build folder, then used the generated Visual Studio project to build all files.
> In Debug, I copied the newly-generated library file into my MinGW's library path.

Have you tried this with other libraries before?

**Comment by Jamesthe1** [comment]
Yes, I have built from source for other libraries. No issues have been recorded for them.

**Comment by sammycage** [comment]
Make sure that you build directory is clean.

```
mkdir build
cd build
cmake .. -G "MinGW Makefiles"
make
```

**Comment by Jamesthe1** [comment]
The following has resolved the issue
