### ISSUE TITLE
NaN in path data causes infinite loop

### ISSUE THREAD

**Issue by ironxu** [sammycage/lunasvg#62]
**### <path d="MNaN NaNaNaN NaN NaN 1 0 NaN NaN NaN NaN NaN 1 0 NaN NaNZ" fill="#CAF0EC"/>**

like thi
[1.svg.txt](https://github.com/sammycage/lunasvg/files/7863123/1.svg.txt)
s

**Comment by sammycage** [comment]
@ironxu Thanks for reporting this horrible problem.
