### ISSUE TITLE
How to set color for bitmap before rendering?

### ISSUE THREAD

**Issue by aeris170** [sammycage/lunasvg#63]
I'm rendering an SVG with the example code yoou provided and it works great, but I would like to alter the output color of the rendered SVG. Is this possible? I'd expect something along the lines of:
```
auto document = Document::loadFromFile(filename);
auto bitmap = document->renderToBitmap(width, height, fgColor, bgColor);
```

**Comment by sammycage** [comment]
I don't understand? What did you mean by fgColor(foreground color)?

**Comment by aeris170** [comment]
> I don't understand? What did you mean by fgColor(foreground color)?

I would like to change the color of rendered bitmap image. I have my SVG's as as black on top of transparent, is it possible to render them with a different color? Like, red or white or blue?

**Comment by sammycage** [comment]
> ```Bitmap renderToBitmap(std::uint32_t width = 0, std::uint32_t height = 0, std::uint32_t backgroundColor = 0x00000000) const;```

`backgroundColor` format is 0xRRGGBBAA

| Name | HexCode | BackgroundColor
| --- | --- | --- |
| Red | #FF0000 | 0xFF0000FF
| Breen | #00FF00 | 0x00FF00FF
| Blue | #0000FF | 0x0000FFFF
| Yellow | #FFFF00 | 0xFFFF00FF
| White | #FFFFFF | 0xFFFFFFFF
| Pink | #FFC0CB | 0xFFC0CBFF

# Example

- Green circle with 80px radius with transparent `black` background

```svg
<svg id="svg1" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
    <circle id="circle1" cx="100" cy="100" r="80" fill="green"/>
</svg>
```

- Render the circle with `yellow` background color

```cpp
auto bitmap = document->renderToBitmap(0, 0, 0xFFFF00FF);
```

![circle-yellow-bg](https://user-images.githubusercontent.com/29164324/149716772-5e256f6b-7908-47a2-a864-00af27ea49ca.png)

- Render the circle with `red` background color

```cpp
auto bitmap = document->renderToBitmap(0, 0, 0xFF0000FF);
```

![circle-red-bg](https://user-images.githubusercontent.com/29164324/149716873-340b25d8-f553-4e2a-8905-2283bc6f9ee9.png)

- Render the circle with `pink` background color

```cpp
auto bitmap = document->renderToBitmap(0, 0, 0xFFC0CBFF);
```

![circle-red-bg](https://user-images.githubusercontent.com/29164324/149718575-d471ba75-3be6-476e-83d5-7e5dfe0771f7.png)

**Comment by aeris170** [comment]
I understand, my initial question was probably not well formulated. I wanted to change the color of "green circle" in the example you provided. Now I see how I can. Since SVG are just markup (I just discovered this, thanks to you), I can loop every every child of <svg> tag set attrib fill="red". That way the whole SVG wil appear red. Thank you. I'm closing this issue since it is not LunaSVG's job to manipulate the SVG.
