### ISSUE TITLE
Opacity attribute is handled incorrectly 

### ISSUE THREAD

**Issue by viktoras-pal** [sammycage/lunasvg#66]
SVG:
```
<svg xmlns="http://www.w3.org/2000/svg" width="200" height="260" viewBox="0 0 200 260">
<rect x="20" y="20" rx="20" ry="20" width="160" height="100" style="fill:blue;stroke:red;stroke-width:10;opacity:0.5" />
<rect x="20" y="140" rx="20" ry="20"  width="160" height="100" style="fill:blue;stroke:red;stroke-width:10;fill-opacity:0.5;stroke-opacity:0.5" />
</svg>
```
LunaSVG:
![curves svg](https://user-images.githubusercontent.com/13905093/153732306-d6c591a4-6f42-4a0d-b797-799bdd8ab5aa.png)
Google Chrome:
![image](https://user-images.githubusercontent.com/13905093/153732131-9c462e42-b1c7-4729-a2af-19423be4ae31.png)

**Comment by sammycage** [comment]
Fixed : 8e7cdfead76f48641baa0611a14284aa409071ca
