### ISSUE TITLE
SVG image rotation

### ISSUE THREAD

**Issue by viktoras-pal** [sammycage/lunasvg#67]
How to rotate a final SVG image so that it would be rendered correctly without cropping?
It would be nice to have a method to render a rotated and scaled SVG image, like this:

`
Bitmap Document::renderToBitmapRotated(double angle, double scale, std::uint32_t backgroundColor) const;
`

**Comment by sammycage** [comment]
```
<svg id="svg1" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">

    <rect id="rect1" x="20" y="20" width="160" height="160" fill="red"/>

</svg>

```

> Original
![rect svg](https://user-images.githubusercontent.com/29164324/153761150-03f7b883-1b30-4303-85c5-30b7d8e8f952.png)

> `Document::rotate(45)`

![rect-rotated svg](https://user-images.githubusercontent.com/29164324/153761234-cd4510e3-9561-42fa-b576-18bcbf331ede.png)

**Comment by sammycage** [comment]
```
<svg id="svg1" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">

    <rect id="rect1" x="20" y="20" width="160" height="160" fill="red"/>

</svg>

```

> Original

![rect svg](https://user-images.githubusercontent.com/29164324/153761150-03f7b883-1b30-4303-85c5-30b7d8e8f952.png)

> `document->rotate(45)`

![rect-rotated svg](https://user-images.githubusercontent.com/29164324/153761234-cd4510e3-9561-42fa-b576-18bcbf331ede.png)

> `document->rotate(45, document->width() / 2.0, document->heigth() / 2.0)`

![rect svg](https://user-images.githubusercontent.com/29164324/153762089-c39feeb7-bccb-4509-93e1-3c16f80b2b9f.png)


> How to rotate a final SVG image so that it would be rendered correctly without cropping?

Is this what you meant by cropping

**Comment by viktoras-pal** [comment]
Yes. The result should be a full square (not clipped with viewBox):
![image](https://user-images.githubusercontent.com/13905093/153762811-957269d0-e862-477d-b2a5-eddbf296e7a2.png)
I have a collection of SVG map symbols and I want to draw them on a map at different rotation angles.

**Comment by sammycage** [comment]
```cpp
Bitmap renderToBitmapRotated(Document* document, double angle, double scale, std::uint32_t bgColor)
{
    const double pi = 3.14159265358979323846;

    double radians = pi * angle / 180.0;
    double sine = std::sin(radians);
    double cosine = std::cos(radians);

    double originalWidth = document->width();
    double originalHeight = document->height();

    double rotatedWidth = cosine * originalWidth + sine * originalHeight;
    double rotatedHeight = cosine * originalHeight + sine * originalWidth;

    document->scale(originalWidth / rotatedWidth, originalHeight / rotatedHeight);

    document->translate(rotatedWidth / 2.0, rotatedHeight / 2.0);
    document->rotate(angle);
    document->translate(-originalWidth / 2.0, -originalHeight / 2.0);

    document->scale(scale, scale);

    Bitmap bitmap(originalWidth, originalHeight);
    document->render(bitmap, {}, bgColor);
    return bitmap;
}
````

Lemme know if it works :)

**Comment by viktoras-pal** [comment]
Thank you. 
I changed Document* to std::unique_ptr<Document>& because there was a compiler error.

I tested it, but the result is not quite what it should be. When scale is 1, the resulting square is smaller than the original. Another problem is that if the viewBox is not square, the resulting shape is skewed:

```
<svg viewBox="0 0 240 140" xmlns="http://www.w3.org/2000/svg">
<rect x="20" y="20" width="100" height="100" style="fill:red;" />
</svg>

```
Original:  
![curves svg](https://user-images.githubusercontent.com/13905093/153933756-e0af1889-5161-471b-9826-1677cb84c8da.png)
After rotation:
![curves svg1](https://user-images.githubusercontent.com/13905093/153935453-b6cceedf-29cc-474d-a7a6-36d00d669ec8.png)

**Comment by sammycage** [comment]
> When scale is 1, the resulting square is smaller than the original. Another problem is that if the viewBox is not square, the resulting shape is skewed:

Because When rotating an image the size changes so I have to scale the image back its original size.

Please try this one with the latest commit 

```cpp
Bitmap renderToBitmapRotated(Document* document, double angle, double scale, std::uint32_t bgColor)
{
    const double pi = 3.14159265358979323846;

    double radians = pi * angle / 180.0;
    double sine = std::sin(radians);
    double cosine = std::cos(radians);

    double originalWidth = document->width();
    double originalHeight = document->height();

    double rotatedWidth = cosine * originalWidth + sine * originalHeight;
    double rotatedHeight = cosine * originalHeight + sine * originalWidth;

    Matrix matrix;
    //matrix.scale(originalWidth / rotatedWidth, originalHeight / rotatedHeight);
    matrix.translate(rotatedWidth / 2.0, rotatedHeight / 2.0);
    matrix.rotate(angle);
    matrix.translate(-originalWidth / 2.0, -originalHeight / 2.0);
    matrix.scale(scale, scale);

    Bitmap bitmap(rotatedWidth, rotatedWidth);
    document->render(bitmap, matrix, bgColor);
    return bitmap;
}
```

N.B the resulting image might be larger than the original image

**Comment by viktoras-pal** [comment]
I made some corrections:
```
Bitmap renderToBitmapRotated(const Document* document, double angle, double scale, std::uint32_t bgColor)
{
    const double pi = 3.14159265358979323846;

    double radians = pi * angle / 180.0;
    double sine = std::abs(std::sin(radians));
    double cosine = std::abs(std::cos(radians));

    double originalWidth = document->width();
    double originalHeight = document->height();

    double rotatedWidth = cosine * originalWidth + sine * originalHeight;
    double rotatedHeight = cosine * originalHeight + sine * originalWidth;

    Matrix matrix;
    matrix.translate(rotatedWidth / 2.0, rotatedHeight / 2.0);
    matrix.rotate(angle);
    matrix.translate(-originalWidth / 2.0, -originalHeight / 2.0);
    matrix.scale(scale, scale);

    std::uint32_t width = static_cast<std::uint32_t>(std::ceil(rotatedWidth));
    std::uint32_t height = static_cast<std::uint32_t>(std::ceil(rotatedHeight));

    Bitmap bitmap(width, height);
    document->render(bitmap, matrix, bgColor);
    return bitmap;
}
```
Now everything works fine except when viewBox is undefined.

**Comment by sammycage** [comment]
```cpp

Bitmap renderToBitmapRotated(Document* document, double angle, double scale, std::uint32_t bgColor)
{
    const double pi = 3.14159265358979323846;

    double radians = pi * angle / 180.0;
    double sine = std::abs(std::sin(radians));
    double cosine = std::abs(std::cos(radians));

    double originalWidth = document->width();
    double originalHeight = document->height();

    double rotatedWidth = cosine * originalWidth + sine * originalHeight;
    double rotatedHeight = cosine * originalHeight + sine * originalWidth;

    double scaledWidth = rotatedWidth * scale;
    double scaledHeight = rotatedHeight * scale;

    Matrix matrix;
    matrix.scale(scaledWidth / rotatedWidth, scaledHeight / rotatedHeight);
    matrix.translate(rotatedWidth / 2.0, rotatedHeight / 2.0);
    matrix.rotate(angle);
    matrix.translate(-originalWidth / 2.0, -originalHeight / 2.0);

    std::uint32_t width = static_cast<std::uint32_t>(std::ceil(scaledWidth));
    std::uint32_t height = static_cast<std::uint32_t>(std::ceil(scaledHeight));

    Bitmap bitmap(width, height);
    document->render(bitmap, matrix, bgColor);
    return bitmap;
}
```

I hope this works

**Comment by viktoras-pal** [comment]
Thank you, it works as expected now.
Example:
```
<svg  width="240" height="140" viewBox="100 0 240 140" xmlns="http://www.w3.org/2000/svg">
<rect x="110" y="10" width="220" height="120" style="fill:red;"  stroke="blue" stroke-width="1" />
</svg>
```
Original:
![curves svg](https://user-images.githubusercontent.com/13905093/154064370-6df79fce-1259-4c41-8533-8be4059b70d9.png)
Scale: 0.5, rotation angles: 0/30/60/90/120
![curves svg00](https://user-images.githubusercontent.com/13905093/154064128-60f0a104-af66-40ec-8784-54b988526516.png) ![curves svg30](https://user-images.githubusercontent.com/13905093/154064167-5ef45650-0b2b-46ce-a41a-adca0cddf952.png) ![curves svg60](https://user-images.githubusercontent.com/13905093/154064231-a7503dfc-7661-48ac-82bb-a9c92f7555e1.png) ![curves svg90](https://user-images.githubusercontent.com/13905093/154064311-e109a43f-24dd-4836-9278-91f54e2d9ab5.png) ![curves svg120](https://user-images.githubusercontent.com/13905093/154064330-327800c1-ec83-48bd-a60a-a27879a154a9.png)

You could include this useful function to your library as a method of Document class.

**Comment by sammycage** [comment]
Thank you for opening this issue <3 <3 <3
