### ISSUE TITLE
Shape is unexpectedly asymmetric

### ISSUE THREAD

**Issue by Pospelove** [sammycage/lunasvg#80]
https://github.com/lichess-org/lila/blob/master/public/piece/cburnett/bK.svg

```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45">
   <g fill="none" fill-rule="evenodd" stroke="#000" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">
      <path d="M22.5 11.63V6" stroke-linejoin="miter" />
      <path d="M22.5 25s4.5-7.5 3-10.5c0 0-1-2.5-3-2.5s-3 2.5-3 2.5c-1.5 3 3 10.5 3 10.5" fill="#000" stroke-linecap="butt" stroke-linejoin="miter" />
      <path d="M11.5 37c5.5 3.5 15.5 3.5 21 0v-7s9-4.5 6-10.5c-4-6.5-13.5-3.5-16 4V27v-3.5c-3.5-7.5-13-10.5-16-4-3 6 5 10 5 10V37z" fill="#000" />
      <path d="M20 8h5" stroke-linejoin="miter" />
      <path d="M32 29.5s8.5-4 6.03-9.65C34.15 14 25 18 22.5 24.5l.01 2.1-.01-2.1C20 18 9.906 14 6.997 19.85c-2.497 5.65 4.853 9 4.853 9" stroke="#ececec" />
      <path d="M11.5 30c5.5-3 15.5-3 21 0m-21 3.5c5.5-3 15.5-3 21 0m-21 3.5c5.5-3 15.5-3 21 0" stroke="#ececec" />
   </g>
</svg>
```

Expected:
![image](https://user-images.githubusercontent.com/37947786/160792355-9f1eb406-2099-46d3-a056-19a9e99c2bb4.png)
Actual:
![image](https://user-images.githubusercontent.com/37947786/160792281-b480ba48-ee33-4758-9aa0-f48272e0dd6e.png)

**Comment by Pospelove** [comment]
Please let me know if any additional info needed

**Comment by Pospelove** [comment]
It works thanks @sammycage!
I'm working on adding lunasvg to vcpkg: https://github.com/microsoft/vcpkg/pull/23867
It would be very helpful if you release 2.3.2 with the fix. I would update my vcpkg PR immediately so they will merge the fixed version. The current PR adds 2.3.1

![image](https://user-images.githubusercontent.com/37947786/160878290-b7d503cb-dc66-40b4-8771-1598c8f72132.png)

**Comment by Pospelove** [comment]
https://user-images.githubusercontent.com/37947786/160879319-0578c463-081e-447b-a48d-0c9ba2c19cd7.png

**Comment by sammycage** [comment]
> It [works](https://user-images.githubusercontent.com/37947786/160879038-48c202bd-acaf-404f-ba72-f77c24455dc6.png) thanks @sammycage! 🤟🏾
> 
> I'm working on adding lunasvg to vcpkg: [microsoft/vcpkg#23867](https://github.com/microsoft/vcpkg/pull/23867) It would be very helpful if you release 2.3.2 with the fix. I would update my vcpkg PR immediately so they will merge the fixed version. The current PR adds 2.3.1

I will try to release a new version

**Comment by sammycage** [comment]
> https://user-images.githubusercontent.com/37947786/160879319-0578c463-081e-447b-a48d-0c9ba2c19cd7.png better screenshot (can't edit prev comment anymore for some reason lol)

Wow 👍🏾
