### ISSUE TITLE
In the following SVG you get black lines between the shapes using the lunasvg

### ISSUE THREAD

**Issue by einhugur** [sammycage/lunasvg#81]
In the following SVG you get black lines between the shapes using the lunasvg. When opening same image in any web browser then the seams between the shapes are clean.

![3199472](https://user-images.githubusercontent.com/42967211/163463751-85557139-5aef-49ab-9ab2-d1693145118c.svg)

**Comment by sammycage** [comment]
`image` tag is not supported

**Comment by einhugur** [comment]
Thanks I had not realized it had image tag, I guess I did not look since it loads almost perfectly!
