### ISSUE TITLE
Contribution: Render SVG to HBITMAP or HICON (from executable/DLL resource) for Win32 API

### ISSUE THREAD

**Issue by Leonard-The-Wise** [sammycage/lunasvg#82]
Hello, since I don't know where to post this, I'd like to give you a small contribution for setting an example on how to render a SVG file to a `Win32` `HBITMAP` (or `HICON`) surface using `GDI+`.

The part of rendering the image was the most easy one (I found out how to in a matter of minutes). The **HARD** part (and here it was really hard to figure out) was cincumventing a nasty bug in `GDI+/Win32 API` that would mangle the Alpha channel data, hence making the image to render with an ugly black background in some specific circunstances. 

***Examples***: 
**1) if I tried to generate an HICON to save a .ico file from SVG, it would render the icon with a completely black background.** And 
**2) if I passed a HBITMAP to [`SetMenuItemBitmaps`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setmenuitembitmaps) (Win32 API) from a SVG generated, it would also get the (ugly) black background. Microsoft even states this function is not supposed to be used with colored bitmaps, but if you setup properly a colored bitmap it WILL work - I tested and use it (see screenshot).** 

![image](https://user-images.githubusercontent.com/99574879/163530554-1b32118c-e9ac-400c-8379-0874bbfcbe5a.png)

*(these are the two cases where I found out there's a problem with conversions. Other uses the images were displaying normally without any extra trick)*. Note: the `UAC SHIELD` icon is the only one not rendered from a SVG file. It was actually retrieved from the Stock Icons Library with `SHGetStockIconInfo` and `LoadImage`.

Then I spent 2 days researching a solution and finally found a single one that worked on [StackOverflow](https://stackoverflow.com/questions/11338009/how-do-i-copy-an-hicon-from-gdi-to-gdi-with-transparency). You actually must perform a workaround with GDI+ `LockBits` to get it to correctly build the Alpha channel from the SVG file (from any HBITMAP to tell the truth). Results are here:

![image](https://user-images.githubusercontent.com/99574879/163530295-714e1d46-770f-45c4-b26c-d40599e33b3b.png)

So, the code bellow might help people trying to integrate LunaSVG into their Windows apps - especially if they are trying to use the images to menu icons as I do. With this, I could even correctly save `.ico` files with full alpha transparency from `HICON`.

***Also, since SVG files are inverted to HBITMAPs surfaces, I also passed a negative height to the `BITMAPINFOHEADER` structure (yeah, nasty trick from Microsoft, hehe) and converted to the compatible colors before generating the images.***

``` C++
    HBITMAP iconToBitmap(HICON hIcon)
    {
        if (!hIcon)
            return NULL;

        ICONINFO iconInfo;
        ZeroMemory(&iconInfo, sizeof(iconInfo));
        GetIconInfo(hIcon, &iconInfo);

        HDC screenDevice = GetDC(NULL);
        HDC hdc = CreateCompatibleDC(screenDevice);
        ReleaseDC(NULL, screenDevice);

        int iconWidth = iconInfo.xHotspot * 2;
        int iconHeight = iconInfo.yHotspot * 2;

        BITMAPINFOHEADER bitmapInfoH = { sizeof(BITMAPINFOHEADER), iconWidth, iconHeight, 1, 32, BI_RGB, 0, 0, 0, 0, 0 };
        BITMAPINFO bitmapInfo = { bitmapInfoH, {} };
        HBITMAP winBitmap = nullptr;
        HGDIOBJ oldHdc = nullptr;
        DWORD* bits = nullptr;

        winBitmap = CreateDIBSection(hdc, &bitmapInfo, DIB_RGB_COLORS, (VOID**)&bits, NULL, 0);
        if (winBitmap)
        {
            // Switch hdc object to point into the bitmap.
            oldHdc = SelectObject(hdc, reinterpret_cast<HGDIOBJ>(winBitmap));
            if (oldHdc)
                DrawIconEx(hdc, 0, 0, hIcon, iconWidth, iconHeight, 0, 0, DI_NORMAL);
        }

        DeleteObject(iconInfo.hbmMask);
        DeleteObject(iconInfo.hbmColor);

        // Restore previous object (state) for HDC, like recommended here: 
        // https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-selectobject
        if (oldHdc)
            SelectObject(hdc, oldHdc);

        DeleteDC(hdc);

        return winBitmap;
    }

    HBITMAP loadSVGFromResource(HMODULE module, int idResource, UINT width, UINT height)
     {
        HICON retval = NULL;
        ULONG_PTR token = 0;
        Gdiplus::GdiplusStartupInput input = NULL;
        Gdiplus::GdiplusStartup(&token, &input, NULL);

        if (token == 0)
            return NULL;

        // Load resource
        auto hResource = FindResourceW(module, MAKEINTRESOURCE(idResource), L"SVG");
        size_t _size = SizeofResource(module, hResource);
        auto hMemory = LoadResource(module, hResource);
        LPVOID ptr = LockResource(hMemory);
        if (!hMemory)
            return NULL;

        auto svgDocument = lunasvg::Document::loadFromData(reinterpret_cast<char*>(ptr));
        lunasvg::Bitmap bmpResult = svgDocument->renderToBitmap(width, height);
        bmpResult.convert(2, 1, 0, 3, false); // Convert to ARGB not premultiplied.

        FreeResource(hMemory);

        // Create compatible bitmap from bmpResult (DIB)
        BITMAPINFOHEADER bitmapInfoH = { sizeof(BITMAPINFOHEADER), static_cast<int>(width), -static_cast<int>(height), 1, 32, BI_RGB, 0, 0, 0, 0, 0 };
        BITMAPINFO bitmapInfo = { bitmapInfoH, {} };
        Gdiplus::Bitmap* bmp = new Gdiplus::Bitmap(&bitmapInfo, reinterpret_cast<void*>(bmpResult.data()));

        // GDI+ will mangle the Alpha channel from our Bitmap, so we must do an extra step to recover it.
         // https://stackoverflow.com/questions/11338009/how-do-i-copy-an-hicon-from-gdi-to-gdi-with-transparency
        Gdiplus::BitmapData lockedBitmapData;
        Gdiplus::Rect rc(0, 0, width, height);
        bmp->LockBits(&rc, Gdiplus::ImageLockModeRead, bmp->GetPixelFormat(), &lockedBitmapData);

        Gdiplus::Bitmap* image = new Gdiplus::Bitmap(lockedBitmapData.Width, lockedBitmapData.Height, lockedBitmapData.Stride,
            PixelFormat32bppARGB, reinterpret_cast<BYTE*>(lockedBitmapData.Scan0));
        
        // Must retrieve as HICON or we lose transparency information. We cast to HBITMAP at the end.
        image->GetHICON(&retval);
        delete bmp, image;
        Gdiplus::GdiplusShutdown(token);

        return iconToBitmap(retval);
    }
```

And it's sister function - that only changes the output format really.

``` C++
    // Load a SVG from resources and convert into an HICON.
    // Files must be included as "SVG" type resource.
    HICON loadSVGFromResourceIcon(HMODULE module, int idResource, UINT width, UINT height)
    {
        HICON retval = NULL;
        ULONG_PTR token = 0;
        Gdiplus::GdiplusStartupInput input = NULL;
        Gdiplus::GdiplusStartup(&token, &input, NULL);

        if (token == 0)
            return NULL;

        // Load resource
        auto hResource = FindResourceW(module, MAKEINTRESOURCE(idResource), L"SVG");
        size_t _size = SizeofResource(module, hResource);
        auto hMemory = LoadResource(module, hResource);
        LPVOID ptr = LockResource(hMemory);
        if (!hMemory)
            return NULL;

        auto svgDocument = lunasvg::Document::loadFromData(reinterpret_cast<char*>(ptr));
        lunasvg::Bitmap bmpResult = svgDocument->renderToBitmap(width, height);
        bmpResult.convert(2, 1, 0, 3, false); // Convert to ARGB not premultiplied.

        FreeResource(hMemory);

        // Use GDI+ to build HBITMAP from the image
        // Image is upside-down, so the trick is to create the header with a negative height.
        BITMAPINFOHEADER bitmapInfoH = { sizeof(BITMAPINFOHEADER), static_cast<int>(width), -static_cast<int>(height), 1, 32, BI_RGB, 0, 0, 0, 0, 0 };
        BITMAPINFO bitmapInfo = { bitmapInfoH, {} };
        Gdiplus::Bitmap* bmp = new Gdiplus::Bitmap(&bitmapInfo, reinterpret_cast<void*>(bmpResult.data()));

        // GDI+ will mangle the Alpha channel from our Bitmap, so we must do an extra step to recover it.
        // https://stackoverflow.com/questions/11338009/how-do-i-copy-an-hicon-from-gdi-to-gdi-with-transparency
        Gdiplus::BitmapData lockedBitmapData;
        Gdiplus::Rect rc(0, 0, width, height);
        bmp->LockBits(&rc, Gdiplus::ImageLockModeRead, bmp->GetPixelFormat(), &lockedBitmapData);

        Gdiplus::Bitmap* image = new Gdiplus::Bitmap(lockedBitmapData.Width, lockedBitmapData.Height, lockedBitmapData.Stride,
            PixelFormat32bppARGB, reinterpret_cast<BYTE*>(lockedBitmapData.Scan0));
        
        // Here we just need to retrieve the HICON back from the second Image.
        image->GetHICON(&retval);
        delete bmp, image;
        Gdiplus::GdiplusShutdown(token);

        return retval;
    }
```

PS: Thank you very much for the library. It's really fast and I could easily integrate in a Notepad++ Plugin of my own (shrinked icon and image sizes by a LOT).

PS2: I double tested and the first function still had the bug if I retrieved a HBITMAP directly from GDI+. 😢 
What I have done to fix it was to retrieve an HICON from the image, and then cast it into a bitmap with a DIB section. All other means I tried I failed, so any ideas here will be welcome. I guess the first function is already slow enough, but if no other way is found, I guess I'll have to stick with this one. =\

I provided the function to convert icons to bitmap along with the **working** versions of my functions. 

Cheers! 😃

**Comment by sammycage** [comment]
Wow!!!

**Comment by sammycage** [comment]
#7 #6

**Comment by Leonard-The-Wise** [comment]
Thanks, sir. The code I was using to render the bitmap was very similar to the one you provided on issue #7. That caused the bug I mentioned here (converting it straight to HBITMAP). So I had to use all of that GDI+ trick to work around it. A pitty this bug is around for so long now and Microsoft seems unable to fix it.

Anyway... I'm glad you liked it. :)

Cheers.
