### ISSUE TITLE
Render mono color SVG with custom color

### ISSUE THREAD

**Issue by gabrielaexile** [sammycage/lunasvg#83]
Is there any way to Render single color SVG with custom color ?

If not then I would like to request such feature.

User interface often uses single color SVG for icons for various of things which then change color depending on Light or Dark mode or enabled or disabled.

**Comment by Leonard-The-Wise** [comment]
I know I can be a bit late, but take a look at this piece of code:
https://github.com/Leonard-The-Wise/NWScript-Npp/blob/f978058f7f5e21a1293341eb43cf4fbdc23f0d43/src/Utils/ColorConvert.cpp#L110

I do dynamic colorization / luminosity changes to all svg icons in my project. To colorize, just convert the color to HSL, and change the Hue, Saturation or Luminosity for the byte, then cast it back.

**Comment by gabrielaexile** [comment]
Thanks,

I somehow missed your mail until now. (sorry about that I did not mean to
ignore your kind response).

I basically patched the lunasvg library to do it for now.  As a temp
solution.
