### ISSUE TITLE
Build error on Win 10 VS 2019

### ISSUE THREAD

**Issue by TechArtistG** [sammycage/lunasvg#89]
Build error:
Error (active)	E0042	operand types are incompatible ("const char *" and "char")	lunasvg	D:\GitHub\lunasvg\source\parser.cpp	774	

Repro:
1. Open a VS command prompt and execute following commands:
git clone https://github.com/sammycage/lunasvg.git
cd lunasvg
mkdir build
cd build
cmake ..
2. Load resultant VS solution and build, will get build errors

**Comment by sammycage** [comment]
Fixed.. Thanks for reporting <3

**Comment by fdwr** [comment]
@TechArtistG Thanks, as I was about to say the same. I see Sammy fixed it here: https://github.com/sammycage/lunasvg/commit/a05bbe8b65d70ac05597af6aa110e27c08cfd853
