### ISSUE TITLE
LINKER ERROR

### ISSUE THREAD

**Issue by kimhao97** [sammycage/lunasvg#9]
I cann't declare VGDocument document. Maybe, I forget .lib files  ? 
My code: 
```
 #include "lunasvg/include/svgdocument.h
 using namespace lunasvg;
 SVGDocument document;
```
However, this won't compile and gives many errors similar to:
Error LNK2019	unresolved external symbol "public: __thiscall lunasvg::SVGDocument::SVGDocument(void)" (??0SVGDocument@lunasvg@@QAE@XZ) referenced in function "void __cdecl `dynamic initializer for 'document''(void)" (??__Edocument@@YAXXZ)

**Comment by sammycage** [comment]
Please take a look at this - https://stackoverflow.com/questions/12573816/what-is-an-undefined-reference-unresolved-external-symbol-error-and-how-do-i-fix

**Comment by sammycage** [comment]
I don't have access to VISUAL STUDIO.
just try this.
build static lib
```
cmake -DBUILD_SHARED_LIB=OFF ..

```
