### ISSUE TITLE
Case where gradient is lost

### ISSUE THREAD

**Issue by ifiddynine** [sammycage/lunasvg#90]
Hi,

I found an issue where a gradient isn't loaded or rendered correctly, see attached repro case.

``` 
<svg width="40" height="40" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
<rect width="40" height="40" rx="6" fill="#18181B"/>
<rect width="40" height="40" rx="6" fill="#9F81DD"/>
<rect width="40" height="40" rx="6" fill="url(#paint0_radial_1325_17657)"/>
<rect width="40" height="40" rx="6" fill="url(#paint1_radial_1325_17657)"/>
<rect width="40" height="40" rx="6" fill="url(#paint2_radial_1325_17657)"/>
<path d="M14 19.25C13.5858 19.25 13.25 19.5858 13.25 20C13.25 20.4142 13.5858 20.75 14 20.75H19.25V26C19.25 26.4142 19.5858 26.75 20 26.75C20.4142 26.75 20.75 26.4142 20.75 26V20.75H26C26.4142 20.75 26.75 20.4142 26.75 20C26.75 19.5858 26.4142 19.25 26 19.25H20.75V14C20.75 13.5858 20.4142 13.25 20 13.25C19.5858 13.25 19.25 13.5858 19.25 14V19.25H14Z" fill="white"/>
<defs>
<radialGradient id="paint0_radial_1325_17657" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(31.8667 33.9535) rotate(-161.408) scale(19.6945 15.4579)">
<stop stop-color="#CE5ACE"/>
<stop offset="1" stop-color="#B139B1" stop-opacity="0"/>
</radialGradient>
<radialGradient id="paint1_radial_1325_17657" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(40 8.60465) rotate(156.196) scale(43.7191 35.479)">
<stop stop-color="#FF075A"/>
<stop offset="1" stop-color="#FC407F" stop-opacity="0"/>
</radialGradient>
<radialGradient id="paint2_radial_1325_17657" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(-2.5133e-07 18.1395) rotate(5.4116) scale(41.9202 87.8269)">
<stop stop-color="#23C9FF"/>
<stop offset="1" stop-color="#60D4FA" stop-opacity="0"/>
</radialGradient>
</defs>
</svg>
```

![add_button](https://user-images.githubusercontent.com/45687559/174075809-98b95271-3939-40f6-9e25-15fc0634f18e.svg)

**Comment by sammycage** [comment]
I reviewed the attached repro case and compared the rendering in Firefox and LunaSVG. However, I'm unable to observe any noticeable differences between the two when the image is rendered.

To better assist you, could you please provide more specific details or highlight the specific bug you are experiencing?

**Comment by sammycage** [comment]
Hi @ifiddynine 

I reviewed the attached repro case and compared the rendering in Firefox and LunaSVG. However, I'm unable to observe any noticeable differences between the two when the image is rendered.

To better assist you, could you please provide more specific details or highlight the specific bug you are experiencing?

**Comment by landenlabs2** [comment]
Several of the w3c test SVGs fail to render at all or are incomplete. 
I only tested 5 w3c test images and only one is 100% accurate, two did not render at all and  2 are incorrect. 
I got the images from the W3C tiny test suite. 
[W3C SVG tiny test suite](https://www.w3.org/Graphics/SVG/WG/wiki/Test_Suite_Overview)

SVGs
![test01](https://github.com/sammycage/lunasvg/assets/20950079/661c3365-bab9-412a-a149-ee49ed4575ed)
![test03](https://github.com/sammycage/lunasvg/assets/20950079/d185f642-efcf-43b1-acab-cf20359a21cb)
![test05](https://github.com/sammycage/lunasvg/assets/20950079/db47b808-7af2-4178-9563-ab47c2282f81)
![test202](https://github.com/sammycage/lunasvg/assets/20950079/f1fd9eb3-0081-4ca2-9cac-7c04d807af7f)
![test207](https://github.com/sammycage/lunasvg/assets/20950079/6268684a-3499-43fc-9c39-cc924670278c)

Conversion to PNG performed on MAC 
![test01 svg](https://github.com/sammycage/lunasvg/assets/20950079/e24c2fe2-2120-4a41-adae-bc54d461a357)
![test03 svg](https://github.com/sammycage/lunasvg/assets/20950079/a50fa2a2-bb58-4f17-a408-33deded61a48)
![test05 svg](https://github.com/sammycage/lunasvg/assets/20950079/9fbdf8e8-cf0e-4cec-bfa0-5f89191a2c57)
![test202 svg](https://github.com/sammycage/lunasvg/assets/20950079/fd40f1ba-f896-48aa-a653-cd3874f34388)
![test207 svg](https://github.com/sammycage/lunasvg/assets/20950079/16577288-99af-403e-b768-da75e2430677)
