### ISSUE TITLE
some SVG paths are not rendered

### ISSUE THREAD

**Issue by jonnyyu** [sammycage/lunasvg#93]
Hi,

I'm trying to use lunasvg in my project. It is nice, but after some testing I found paths are not rendered correctly for some SVGs. 

For example, This is one of the SVG file, rendered by browser. 
![0005C02E5F316AAD_FA37E9835D5FC5D0_324957](https://user-images.githubusercontent.com/2011471/176629213-e4c0fb2f-337e-4933-be85-06aa48bea839.svg)

This is the image rendered by `svg2png`
![0005C02E5F316AAD_FA37E9835D5FC5D0_324957 svg](https://user-images.githubusercontent.com/2011471/176629509-fc292ab8-01b3-40d6-bdf2-71500e11a8b9.png)

I did some debugging, the problem seems can be narrowed down to the snippets below:
This SVG snippet should draw a red line and a small arc, but svg2png draws nothing.
```
<svg width="220px" height="220px" xmlns="http://www.w3.org/2000/svg" version="1.1" fill="none" stroke="red" >
    <path d="
        M68 50
        L147 74
        M68 50
        A9 9 287 0 0 63 50
    "/>
</svg>
```
If I change it to two paths, it works.
```
<svg width="220px" height="220px" xmlns="http://www.w3.org/2000/svg" version="1.1" fill="none" stroke="red" >
    <path d="
        M68 50
        L147 74
    " />
    <path d="
        M68 50
        A9 9 287 0 0 63 50
    " />
</svg>
```

I'm using master HEAD. Thanks for looking into it!

**Comment by sammycage** [comment]
I will take a closer look at it... Thank you for reporting this wonderful issue

**Comment by sammycage** [comment]
Can you please send me the complete file
