### ISSUE TITLE
Performance issue in rendering files using sw_ft_raster.c 

### ISSUE THREAD

**Issue by zalsaeed** [sammycage/lunasvg#94]
We are testing LunaSVG for performance issues, evaluating a new technique for finding "worst case" inputs. We generated several inputs that appear to trigger an infinite loop. Looking into one of the examples we have (see [id-000709-1](https://user-images.githubusercontent.com/24327078/184371741-41bb5161-efec-48b5-8a1f-bb2c4a478979.svg)), the infinite loop appears in  [sw_ft_raster.c, lines 577-624](https://github.com/sammycage/lunasvg/blob/7417baa0aff477f361e44e2aa793fdb0c7aae352/3rdparty/software/sw_ft_raster.c#L577) (`while (ex1 != ex2 || ey1 != ey2);`). 
​
In our observation, `ex1` is getting smaller (more negative) and moving away from `ex2`, while `ey1` is not changing.  Neither `ex1` nor `ey1` is moving closer to the  `ex2` or `ey2`.   
​
We believe other inputs ([id-000534](https://user-images.githubusercontent.com/24327078/184371042-16738226-0667-4b69-b781-3b7a22169e3c.svg), [id-000555](https://user-images.githubusercontent.com/24327078/184371046-de0f1279-b3d1-498e-9657-9538650199e7.svg), [id-000588](https://user-images.githubusercontent.com/24327078/184371050-0982adb9-bc68-4e0f-a3e9-4f8982f3e43a.svg), and [id-000614](https://user-images.githubusercontent.com/24327078/184371053-caedcffa-cbf8-4369-925a-8285afececd8.svg)) trigger the same issue. However, we didn't profile these yet. 
​
Please note that all the input samples provided have been tested with other SVG renderers such as Chrome and these renderers 
 were able to render the files in fractions of a second.

**Comment by sammycage** [comment]
Fixed... Thank you so much for reporting this issue <3 <3
