### ISSUE TITLE
After calling the function Document::scale() the original SVG canvas is not recalculated

### ISSUE THREAD

**Issue by hobbitdev** [sammycage/lunasvg#95]
After calling the function Document::scale() the original SVG canvas is not recalculated, this leads to a wrong bitmap size calling this function: `auto bitmap = document->renderToBitmap();`

![image](https://user-images.githubusercontent.com/33904565/185407441-b8806c1a-e00f-4db7-a6bf-7635eaf027fd.png)

Regards
Rossano

**Comment by sammycage** [comment]
`Document::renderToBitmap` is for dummies... `Document` matrix methods will be removed soon.

For higher rendering, use `Document::render` instead.

``cpp

    Matrix matrix;
    matrix.scale(0.5, 0.5);

    auto scalex = std::sqrt(matrix.a * matrix.a + matrix.c * matrix.c);
    auto scaley = std::sqrt(matrix.b * matrix.b + matrix.d * matrix.d);

    int width = document->width() * scalex;
    int height = document->height() * scaley;
    Bitmap bitmap(width, height);
    bitmap.clear(0x8080FFFF);
    document->render(bitmap, matrix);
``

**Comment by hobbitdev** [comment]
@sammycage Thank you

It works as expected

**Comment by sammycage** [comment]
@hobbitdev See https://github.com/sammycage/lunasvg/issues/96#issuecomment-1220314547
