### ISSUE TITLE
After calling the function Document::rotate() the original SVG canvas is not recalculated

### ISSUE THREAD

**Issue by hobbitdev** [sammycage/lunasvg#96]
After calling the function Document::rotate() the original SVG canvas is not recalculated, this leads to a wrong bitmap size calling this function: `auto bitmap = document->renderToBitmap();`
If it could be possible to inflate the SVG canvas accordingly with its rotation, the two parameters (cx & cy) to translate the image in ::rotate() wouldn’t make sense.

remark: even using the two parameters called cx and cy it is not possible to arrange certain images after a rotation.

![image](https://user-images.githubusercontent.com/33904565/185408041-4ab9a461-bbc2-4812-a388-39e362b01743.png)

Regards
Rossano

**Comment by sammycage** [comment]
Use `Document::render` instead.

Example :

## Rotate centered

```cpp

Matrix matrix;
matrix.rotate(45, document->width() / 2, document->height() / 2);

Box box(0, 0, document->width(), document->height());
box.transform(matrix);

auto width ​= static_cast<int>(std::ceil(box.x + box.w));
auto height = static_cast<int>(std::ceil(box.y + box.h));

Bitmap bitmap(width, height);
document->render(bitmap, matrix);

```

## Horizontal Flip

```cpp

Matrix matrix;
matrix.translate(document->width(), 0);
matrix.scale(-1, 1);

auto width ​= static_cast<int>(std::ceil(document->width()));
auto height = static_cast<int>(std::ceil(document->height()));

Bitmap bitmap(width, height);
document->render(bitmap, matrix);

```

## Vertical Flip

```cpp

Matrix matrix;
matrix.translate(0, document->height());
matrix.scale(1, -1);

auto width ​= static_cast<int>(std::ceil(document->width()));
auto height = static_cast<int>(std::ceil(document->height()));

Bitmap bitmap(width, height);
document->render(bitmap, matrix);

```

**Comment by hobbitdev** [comment]
Thank you @sammycage for your examples
They work well !
